const {test}=require('node:test'),assert=require('node:assert/strict');
const {register,emailLockId}=require('./account-security');
class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
function fixture(){
 const records=new Map([['users/u',{email:'old@example.test',schoolId:'s',role:'teacher',status:'active',staffId:'staff',assignedClassIds:['c1']}],['schools/s/staff/staff',{userUid:'u',email:'contact@example.test',name:'Teacher'}]]);
 const authUsers=new Map([['u',{uid:'u',email:'old@example.test',emailVerified:true,providerData:[{providerId:'password'}]}]]);
 const ref=path=>({path,doc:id=>ref(path+'/'+id),collection:name=>ref(path+'/'+name),where:(key,op,value)=>({...ref(path),filter:[key,value]})});
 const read=async ref=>ref.path.split('/').length%2?{docs:[...records].filter(([key,value])=>key.startsWith(ref.path+'/')&&key.split('/').length===ref.path.split('/').length+1&&(!ref.filter||value[ref.filter[0]]===ref.filter[1])).map(([key,value])=>({id:key.split('/').at(-1),data:()=>structuredClone(value)}))}:{exists:records.has(ref.path),data:()=>structuredClone(records.get(ref.path))};
 let tail=Promise.resolve(),failCommit=false;
 const db={collection:ref,runTransaction:fn=>{const run=tail.then(async()=>{const writes=[];const tx={get:read,set:(ref,data)=>writes.push([ref.path,data,false]),update:(ref,data)=>writes.push([ref.path,data,true])};const result=await fn(tx);if(failCommit)throw Error('injected commit failure');for(const [key,data,merge]of writes){const value=merge?{...records.get(key)}:{};for(const [field,entry]of Object.entries(data))if(entry==='__delete__')delete value[field];else value[field]=entry;records.set(key,value);}return result;});tail=run.catch(()=>{});return run;}};
 const admin={auth:()=>({getUser:async uid=>{if(!authUsers.has(uid))throw Error('missing auth');return structuredClone(authUsers.get(uid));},getUserByEmail:async email=>{const user=[...authUsers.values()].find(user=>user.email.toLowerCase()===email);if(user)return structuredClone(user);throw Object.assign(Error('missing auth'),{code:'auth/user-not-found'});}}),firestore:{FieldValue:{serverTimestamp:()=>123,delete:()=>'__delete__'}}};
 const handlers=register({db,admin,onCall:(_,fn)=>fn,HttpsError});
 const req=(data={},uid='u',extra={})=>({auth:{uid,token:{email:authUsers.get(uid)?.email,auth_time:Math.floor(Date.now()/1000),...extra}},data});
 return {records,authUsers,handlers,req,setFail:()=>failCommit=true,lock:email=>records.get('schools/s/identityEmails/'+emailLockId(email))};
}
test('email preparation reserves target while retaining current account and school identity',async()=>{const f=fixture(),before=structuredClone(f.records.get('users/u'));const result=await f.handlers.prepareLoginEmailChange(f.req({newEmail:' NEW@Example.Test '}));assert.equal(result.newEmail,'new@example.test');assert.equal(f.lock('new@example.test').uid,'u');assert.equal(f.lock('old@example.test').uid,'u');assert.equal(f.records.get('users/u').email,before.email);assert.equal(f.records.get('users/u').staffId,before.staffId);assert.equal(f.authUsers.get('u').email,before.email);});
test('no sign-in, stale authentication and mismatched token cannot reserve email',async()=>{for(const request of [{data:{newEmail:'new@example.test'}},fixture().req({newEmail:'new@example.test'},'u',{auth_time:1}),fixture().req({newEmail:'new@example.test'},'u',{email:'forged@example.test'})]){const f=fixture();await assert.rejects(f.handlers.prepareLoginEmailChange(request));assert.equal(f.records.size,2);}});
test('disabled school account, disabled Auth user and Google-only user cannot prepare change',async()=>{for(const kind of ['membership','auth','google']){const f=fixture();if(kind==='membership')f.records.get('users/u').status='disabled';if(kind==='auth')f.authUsers.get('u').disabled=true;if(kind==='google')f.authUsers.get('u').providerData=[{providerId:'google.com'}];await assert.rejects(f.handlers.prepareLoginEmailChange(f.req({newEmail:'new@example.test'})));assert(!f.lock('new@example.test'));}});
test('global Auth duplicates and pending active disabled school duplicates block reservations',async()=>{for(const kind of ['auth','pending','active','disabled','lock']){const f=fixture();if(kind==='auth')f.authUsers.set('other',{uid:'other',email:'new@example.test'});else if(kind==='lock')f.records.set('schools/s/identityEmails/'+emailLockId('new@example.test'),{uid:'other'});else f.records.set('users/other',{email:' NEW@example.test ',schoolId:'s',role:'teacher',status:kind});await assert.rejects(f.handlers.prepareLoginEmailChange(f.req({newEmail:'new@example.test'})),error=>error.code==='already-exists');assert(!f.records.get('users/u').pendingLoginEmail);}});
test('simultaneous requests from different identities cannot reserve the same address',async()=>{const f=fixture();f.authUsers.set('other',{uid:'other',email:'other@example.test',emailVerified:true,providerData:[{providerId:'password'}]});f.records.set('users/other',{email:'other@example.test',schoolId:'s',role:'teacher',status:'active'});const result=await Promise.allSettled(['u','other'].map(uid=>f.handlers.prepareLoginEmailChange(f.req({newEmail:'new@example.test'},uid))));assert.equal(result.filter(x=>x.status==='fulfilled').length,1);assert.equal(result.find(x=>x.status==='rejected').reason.code,'already-exists');});
test('verified new email reconciliation retains UID, assignments, Staff link and contact email',async()=>{const f=fixture();await f.handlers.prepareLoginEmailChange(f.req({newEmail:'new@example.test'}));f.authUsers.get('u').email='new@example.test';const result=await f.handlers.synchronizeLoginEmail(f.req());assert.equal(result.email,'new@example.test');assert.equal(result.pendingEmail,'');assert.equal(f.records.get('users/u').pendingLoginEmail,undefined);assert.equal(f.records.get('users/u').staffId,'staff');assert.deepEqual(f.records.get('users/u').assignedClassIds,['c1']);assert.equal(f.records.get('schools/s/staff/staff').email,'contact@example.test');assert.equal(f.lock('old@example.test').uid,'u');assert.equal(f.lock('new@example.test').status,'active');});
test('unverified new email cannot change membership or identity locks',async()=>{const f=fixture();f.authUsers.get('u').email='new@example.test';f.authUsers.get('u').emailVerified=false;await assert.rejects(f.handlers.synchronizeLoginEmail(f.req()),error=>error.code==='failed-precondition');assert.equal(f.records.get('users/u').email,'old@example.test');assert(!f.lock('new@example.test'));});
test('refresh before verification retains pending target and existing login email',async()=>{const f=fixture();await f.handlers.prepareLoginEmailChange(f.req({newEmail:'new@example.test'}));const result=await f.handlers.synchronizeLoginEmail(f.req());assert.equal(result.email,'old@example.test');assert.equal(result.pendingEmail,'new@example.test');});
test('verification retries and email recovery retain reservations and stay idempotent',async()=>{const f=fixture();await f.handlers.prepareLoginEmailChange(f.req({newEmail:'new@example.test'}));f.authUsers.get('u').email='new@example.test';await f.handlers.synchronizeLoginEmail(f.req());const before=structuredClone([...f.records]);await f.handlers.synchronizeLoginEmail(f.req());assert.deepEqual([...f.records],before);f.authUsers.get('u').email='old@example.test';await f.handlers.synchronizeLoginEmail(f.req());assert.equal(f.records.get('users/u').email,'old@example.test');assert.equal(f.lock('new@example.test').uid,'u');});
test('commit failure cannot leave partially reserved credentials',async()=>{const f=fixture();f.setFail();await assert.rejects(f.handlers.prepareLoginEmailChange(f.req({newEmail:'new@example.test'})),/commit failure/);assert.equal(f.records.size,2);assert.equal(f.records.get('users/u').email,'old@example.test');});
test('unverified reservations are bounded but the same address can be resent',async()=>{const f=fixture();for(let i=0;i<3;i++)await f.handlers.prepareLoginEmailChange(f.req({newEmail:'new'+i+'@example.test'}));await assert.rejects(f.handlers.prepareLoginEmailChange(f.req({newEmail:'fourth@example.test'})),error=>error.code==='resource-exhausted');await f.handlers.prepareLoginEmailChange(f.req({newEmail:'new0@example.test'}));assert.equal(f.records.get('users/u').pendingLoginEmail,'new0@example.test');});
test('missing membership email can be repaired from authoritative Auth rather than client input',async()=>{const f=fixture();delete f.records.get('users/u').email;f.authUsers.get('u').emailVerified=false;const result=await f.handlers.synchronizeLoginEmail(f.req({email:'forged@example.test',schoolId:'other'}));assert.equal(result.email,'old@example.test');assert.equal(result.schoolId,'s');assert(!f.lock('forged@example.test'));});
