const {test}=require('node:test'),assert=require('node:assert/strict'),{register,privatePath,revoke}=require('./private-images');
function fixture(role='headteacher'){const writes=[],state={role,status:'active',schoolId:'s'},file={name:'schools/s/student-photos/c/p',bucket:{name:'test-bucket'},metadata:{metageneration:'1',generation:'1',metadata:{firebaseStorageDownloadTokens:'old'}},async getMetadata(){return [this.metadata];},async setMetadata(data,opts){writes.push({data,opts});delete this.metadata.metadata.firebaseStorageDownloadTokens;}};const db={collection:name=>({doc:id=>({get:async()=>({data:()=>state}),collection:()=>({doc:()=>({set:async()=>{}})})})})},bucket={getFiles:async()=>[[file],{}],file:()=>file},admin={storage:()=>({bucket:()=>bucket})},HttpsError=class extends Error{constructor(code,msg){super(msg);this.code=code;}},h=register({db,admin,HttpsError,onCall:(_,fn)=>fn,onObjectFinalized:(_,fn)=>fn,onObjectMetadataUpdated:(_,fn)=>fn});return {h,writes,state,file,req:{auth:{uid:'head'},data:{expectedUid:'head',expectedSchoolId:'s'}}};}
test('old-link maintenance is scoped to active head membership and current school',async()=>{for(const role of ['teacher','guest']){const f=fixture(role);await assert.rejects(f.h.revokeSchoolImageLinks(f.req),e=>e.code==='permission-denied');assert.equal(f.writes.length,0);}const f=fixture();await assert.rejects(f.h.revokeSchoolImageLinks({...f.req,data:{expectedUid:'head',expectedSchoolId:'other'}}),e=>e.code==='failed-precondition');assert.equal(f.writes.length,0);});
test('maintenance removes tokens with a metadata precondition and preserves bytes',async()=>{const f=fixture();const result=await f.h.revokeSchoolImageLinks(f.req);assert.equal(result.revoked,1);assert.equal(result.complete,true);assert.equal(f.writes[0].data.metadata.firebaseStorageDownloadTokens,null);assert.equal(f.writes[0].opts.ifMetagenerationMatch,1);});
test('server upload protection ignores unrelated objects and old generations',async()=>{const f=fixture();await f.h.protectSchoolImageUpload({data:{name:'exports/file',bucket:'bucket',generation:'1'}});assert.equal(f.writes.length,0);f.file.metadata.generation='2';await f.h.protectSchoolImageUpload({data:{name:f.file.name,bucket:'bucket',generation:'1'}});assert.equal(f.writes.length,0);await f.h.protectSchoolImageUpload({data:{name:f.file.name,bucket:'bucket',generation:'2'}});assert.equal(f.writes.length,1);});
test('a failed token mutation never reports completed maintenance',async()=>{const f=fixture();f.file.setMetadata=async()=>{throw Error('storage denied');};await assert.rejects(f.h.revokeSchoolImageLinks(f.req));});
test('private image scopes exclude foreign service objects and traversal',()=>{assert(privatePath('schools/s/student-photos/c/p'));assert(!privatePath('exports/s/photo'));assert(!privatePath('schools/s/ledger/doc'));});

test('metadata updates use the same private token protection as new uploads',async()=>{const f=fixture();await f.h.protectSchoolImageMetadata({data:{name:f.file.name,bucket:'bucket',generation:'1'}});assert.equal(f.writes.length,1);await f.h.protectSchoolImageMetadata({data:{name:f.file.name,bucket:'bucket',generation:'1'}});assert.equal(f.writes.length,1);});
