const {test}=require('node:test'),assert=require('node:assert/strict'),{register}=require('./school-registration');
class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
function fixture(){const records=new Map();let fail=false,verified=true;const ref=path=>({path,id:path.split('/').at(-1),collection:n=>ref(path+'/'+n),doc:id=>ref(path+'/'+id),where:(field,op,value)=>({...ref(path),filter:[field,value],limit:()=>({...ref(path),filter:[field,value]})})});const db={collection:ref,runTransaction:async fn=>{const writes=[];const tx={get:async r=>{assert.equal(writes.length,0,'all reads precede writes');if(r.filter)return {docs:[...records].filter(([k,v])=>k.startsWith(r.path+'/')&&k.split('/').length===2&&v[r.filter[0]]===r.filter[1]).map(([k,v])=>({id:k.split('/').at(-1),data:()=>structuredClone(v)}))};return {exists:records.has(r.path),data:()=>structuredClone(records.get(r.path))};},set:(r,v)=>writes.push([r.path,{...records.get(r.path),...v}]),create:(r,v)=>{assert(!records.has(r.path));writes.push([r.path,v]);}};const result=await fn(tx);if(fail)throw Error('commit failed');for(const [k,v] of writes)records.set(k,v);return result;}};const handlers=register({db,HttpsError,onCall:(_,f)=>f,admin:{auth:()=>({getUser:async uid=>({uid,email:'synthetic@example.test',emailVerified:verified,disabled:false})}),firestore:{FieldValue:{serverTimestamp:()=>123}}}});const req={auth:{uid:'test',token:{email_verified:true}},data:{schoolName:'PILOT LEDGER TEST',address:'',email:'',requestId:'request001'}};return {records,req,run:r=>handlers.registerSchoolSafe(r||req),setFail:()=>fail=true,setUnverified:()=>verified=false};}
test('fresh verified registration atomically creates owner, school, code and receipt; retry is idempotent',async()=>{const f=fixture(),r=await f.run();assert.equal(f.records.get('users/test').role,'headteacher');assert.equal(f.records.get('schools/'+r.schoolId).ownerUid,'test');assert.equal(f.records.get('joinCodes/'+r.joinCode).schoolId,r.schoolId);assert.equal(f.records.size,4);assert.deepEqual(await f.run(),r);assert.equal(f.records.size,4);});
test('removed teacher can recover the exact owner-matched incomplete school without another school',async()=>{const f=fixture();f.records.set('users/test',{status:'removed',createdAt:12});f.records.set('schools/orphan',{ownerUid:'test',profile:{schoolName:'PILOT LEDGER TEST',address:'',email:''},joinCode:'ABC-123',subscription:{plan:'free',status:'inactive'}});const r=await f.run();assert.equal(r.schoolId,'orphan');assert.equal(r.recoveredPartial,true);assert.equal([...f.records.keys()].filter(k=>/^schools\/[^/]+$/.test(k)).length,1);assert.equal(f.records.get('users/test').createdAt,12);});
test('active, pending and disabled school memberships cannot self-promote or change school',async()=>{for(const status of ['active','pending','disabled']){const f=fixture();f.records.set('users/test',{status,role:'teacher',schoolId:'real-school'});await assert.rejects(f.run(),e=>e.code==='permission-denied');assert.equal(f.records.size,1);}});
test('unverified token or revoked verification cannot create a school',async()=>{for(const mode of ['token','live']){const f=fixture();if(mode==='token')f.req.auth.token.email_verified=false;else f.setUnverified();await assert.rejects(f.run(),e=>['failed-precondition','permission-denied'].includes(e.code));assert.equal(f.records.size,0);}});
test('commit failure leaves all four registration documents absent',async()=>{const f=fixture();f.setFail();await assert.rejects(f.run(),/commit failed/);assert.equal(f.records.size,0);});
test('changed retry details or detached replay cannot reuse registration authority',async()=>{const f=fixture();await f.run();f.req.data.schoolName='Changed';await assert.rejects(f.run(),e=>e.code==='failed-precondition');f.req.data.schoolName='PILOT LEDGER TEST';f.records.set('users/test',{status:'removed'});await assert.rejects(f.run(),e=>e.code==='permission-denied');});
test('another owner orphan cannot be adopted',async()=>{const f=fixture();f.records.set('schools/foreign',{ownerUid:'other',profile:{schoolName:'PILOT LEDGER TEST'},joinCode:'ABC-123',subscription:{plan:'free',status:'inactive'}});const r=await f.run();assert.notEqual(r.schoolId,'foreign');assert.equal(f.records.get('schools/foreign').ownerUid,'other');});
test('multiple matching orphans require review and do not mutate membership',async()=>{const f=fixture();for(const id of ['a','b'])f.records.set('schools/'+id,{ownerUid:'test',profile:{schoolName:'PILOT LEDGER TEST'},joinCode:'ABC-123',subscription:{plan:'free',status:'inactive'}});await assert.rejects(f.run(),e=>e.code==='failed-precondition');assert(!f.records.has('users/test'));});
test('missing authentication and invalid request IDs fail without writes',async()=>{const f=fixture();await assert.rejects(f.run({...f.req,auth:null}),e=>e.code==='unauthenticated');f.req.data.requestId='bad/path';await assert.rejects(f.run(),e=>e.code==='invalid-argument');assert.equal(f.records.size,0);});
