const {test}=require('node:test'),assert=require('node:assert/strict');
const {register}=require('./weekly-supervision');
class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
function fixture(){
 const records=new Map([['users/head',{status:'active',role:'headteacher',schoolId:'s'}],['users/teacher',{status:'active',role:'teacher',schoolId:'s',displayName:'Teacher'}],['users/otherTeacher',{status:'active',role:'teacher',schoolId:'s'}],['users/disabled',{status:'disabled',role:'headteacher',schoolId:'s'}],['schools/s',{ownerUid:'head'}]]);
 const ref=(path,filters=[],order='',limit=Infinity)=>({path,filters,order,limitN:limit,collection:n=>ref(path+'/'+n),doc:n=>ref(path+'/'+n),where:(k,op,v)=>ref(path,[...filters,[k,v]],order,limit),orderBy:k=>ref(path,filters,k,limit),limit:n=>ref(path,filters,order,n)});
 let failCommit=false,tail=Promise.resolve();
 const db={collection:ref,runTransaction:fn=>{
  const result=tail.catch(()=>{}).then(async()=>{const writes=[];const tx={get:async r=>{assert.equal(writes.length,0,'transaction reads must precede writes');if(r.path.split('/').length%2===0)return {exists:records.has(r.path),data:()=>structuredClone(records.get(r.path))};let rows=[...records].filter(([k,v])=>k.startsWith(r.path+'/')&&k.split('/').length===r.path.split('/').length+1&&r.filters.every(([key,value])=>v[key]===value));if(r.order)rows.sort((a,b)=>String(b[1][r.order]).localeCompare(String(a[1][r.order])));return {docs:rows.slice(0,r.limitN).map(([k,v])=>({id:k.split('/').at(-1),data:()=>structuredClone(v)}))};},set:(r,v)=>writes.push([r.path,v])};const result=await fn(tx);if(failCommit)throw Error('Commit failed');writes.forEach(([p,v])=>records.set(p,structuredClone(v)));return result;});tail=result;return result;
 }};
 const handlers=register({db,HttpsError,onCall:(_,fn)=>fn,admin:{firestore:{FieldValue:{serverTimestamp:()=>123}}}});
 const req=(data,uid='head')=>({auth:uid?{uid}:null,data:{expectedUid:uid,expectedSchoolId:'s',requestId:'request-'+Math.random().toString(36).slice(2),...data}});
 const update=(data,uid)=>handlers.saveWeeklySupervision(req(data,uid));
 records.get('users/teacher').staffId='staff1';records.get('users/otherTeacher').staffId='staff2';for(const [p,v] of Object.entries({'schools/s/staff/staff1':{name:'Teacher One'},'schools/s/staff/staff2':{name:'Teacher Two'},'schools/s/classes/c1':{name:'Class 4'},'schools/s/subjects/math':{name:'Mathematics'}}))records.set(p,v);
 const item=()=>update({action:'createItem',id:'stock-item-01',code:'BOOK',name:'Exercise books',unit:'pieces',category:'Stationery',quantityMilli:10000,minimumMilli:2000,unitCost:300});
 return {records,handlers,req,update,item,fail:()=>failCommit=true};
}
const valid=()=>({staffId:'staff1',classId:'c1',week:'2026-10-05',year:'2026/2027',term:'1',checkedOn:'2026-10-09',lessonReviewed:true,lessonStatus:'submitted',lessonNote:'Reviewed',registerReviewed:true,registerStatus:'up_to_date',registerNote:'Checked',feedback:'Good progress',followUpOn:'2026-10-12',followUpStatus:'open',assessments:[{subjectId:'math',exercises:4,assessments:1,booksChecked:10,booksMarked:8,note:'Complete marking'}]});
const get=(f,uid='head',week='2026-10-05')=>f.handlers.getWeeklySupervision(f.req({week},uid));
test('official weekly checks retain subject counts, follow-up and server-resolved names',async()=>{const f=fixture(),r=await f.update({...valid(),staffName:'FORGED'}),result=await get(f);assert.equal(result.records.length,1);assert.equal(result.records[0].id,r.id);assert.equal(result.records[0].staffName,'Teacher One');assert.equal(result.records[0].assessments[0].exercises,4);assert.equal(result.records[0].assessments[0].booksMarked,8);assert.equal(result.records[0].updatedBy,'head');assert.equal(result.records[0].followUpStatus,'open');});
test('same save retry is idempotent and altered retry is rejected',async()=>{const f=fixture(),req=f.req(valid());const first=await f.handlers.saveWeeklySupervision(req);assert.deepEqual(await f.handlers.saveWeeklySupervision(req),first);assert.equal([...f.records.keys()].filter(k=>k.includes('/supervisionHistory/')).length,1);await assert.rejects(f.handlers.saveWeeklySupervision({...req,data:{...req.data,feedback:'Changed'}}),e=>e.code==='failed-precondition');});
test('duplicate week for teacher and class cannot create or overwrite a second record',async()=>{const f=fixture();await f.update(valid());await assert.rejects(f.update({...valid(),feedback:'Overwrite'}),e=>e.code==='aborted');assert.equal((await get(f)).records[0].feedback,'Good progress');await f.update({...valid(),week:'2026-10-12',checkedOn:'2026-10-12'});assert.equal((await get(f,'head','2026-10-12')).records.length,1);});
test('revision check prevents concurrent edits and preserves immutable audit history',async()=>{const f=fixture(),first=await f.update(valid());const results=await Promise.allSettled(['A','B'].map(feedback=>f.update({...valid(),...first,feedback})));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.code,'aborted');const history=[...f.records].filter(([k])=>k.includes('/supervisionHistory/')).map(([,v])=>v);assert.equal(history.length,2);assert.equal(history[1].before.feedback,'Good progress');assert.equal((await get(f)).records[0].revision,1);});
test('teacher reads own current staff link only and cannot write checks',async()=>{const f=fixture();await f.update(valid());await f.update({...valid(),staffId:'staff2'});const one=await get(f,'teacher'),two=await get(f,'otherTeacher');assert.equal(one.records.length,1);assert.equal(one.records[0].staffId,'staff1');assert.equal(two.records[0].staffId,'staff2');assert.deepEqual(one.staff,[]);assert.deepEqual(one.classes,[]);await assert.rejects(f.update(valid(),'teacher'),e=>e.code==='permission-denied');f.records.get('users/teacher').staffId='staff2';assert.equal((await get(f,'teacher')).records[0].staffId,'staff2');});
test('unlinked teachers see no other records',async()=>{const f=fixture();await f.update(valid());delete f.records.get('users/teacher').staffId;const result=await get(f,'teacher');assert.equal(result.unlinked,true);assert.deepEqual(result.records,[]);});
test('unauthenticated, inactive, changed account and cross-school calls cannot read or save',async()=>{for(const kind of ['noauth','disabled','school','uid']){const f=fixture(),req=f.req({...valid()});if(kind==='noauth')req.auth=null;if(kind==='disabled')req.auth.uid='disabled';if(kind==='school')req.data.expectedSchoolId='other';if(kind==='uid')req.data.expectedUid='other';await assert.rejects(f.handlers.saveWeeklySupervision(req));await assert.rejects(f.handlers.getWeeklySupervision(req));assert.equal([...f.records.keys()].filter(k=>k.includes('/weeklySupervision/')).length,0);}});
test('bad dates, counts, check choices and duplicate subjects fail without writes',async()=>{const bad=[{week:'2026-10-06'},{checkedOn:'2026-02-30'},{checkedOn:'2026-10-01'},{followUpOn:'2026-10-08'},{lessonReviewed:'yes'},{lessonStatus:'other'},{registerStatus:'not_checked'},{assessments:[{...valid().assessments[0],exercises:1.5}]},{assessments:[{...valid().assessments[0],booksMarked:11}]},{assessments:[valid().assessments[0],valid().assessments[0]]}];for(const changes of bad){const f=fixture(),before=structuredClone([...f.records]);await assert.rejects(f.update({...valid(),...changes}));assert.deepEqual([...f.records],before);}});
test('foreign or deleted staff, classes and subjects cannot be selected',async()=>{for(const changes of [{staffId:'foreign'},{classId:'foreign'},{assessments:[{...valid().assessments[0],subjectId:'foreign'}]}]){const f=fixture();await assert.rejects(f.update({...valid(),...changes}),e=>e.code==='not-found');}});
test('failed transaction commits no partial supervision record or receipt',async()=>{const f=fixture(),before=structuredClone([...f.records]);f.fail();await assert.rejects(f.update(valid()),/Commit failed/);assert.deepEqual([...f.records],before);});
