const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'account-security.js'),'utf8');
function fixture(){
 const calls=[],user={uid:'u',email:'old@example.test',providerData:[{providerId:'password'}],reauthenticateWithCredential:async credential=>calls.push(['reauthenticate',credential.provider]),getIdToken:async forced=>calls.push(['token',forced]),updatePassword:async()=>calls.push(['password']),verifyBeforeUpdateEmail:async(email,settings)=>calls.push(['verify',email,settings.url]),reload:async()=>calls.push(['reload'])};
 const firebase={auth:Object.assign(()=>({currentUser:user}),{EmailAuthProvider:{credential:()=>({provider:'password'})}})};
 const ctx={console,URLSearchParams,document:{getElementById:()=>null},location:{origin:'https://school.test',search:''},firebase,safetyCall:async(name,data)=>{calls.push(['call',name,data]);return {newEmail:data.newEmail,email:user.email,schoolId:'s'};},currentUid:'u',currentSchoolId:'s',currentUserData:{schoolId:'s',role:'teacher'},saveVerifiedLocalSession(){},refreshProfileMenu(){}};
 vm.createContext(ctx);vm.runInContext(source,ctx);return {ctx,user,calls};
}
test('password change reauthenticates before updating and keeps the same UID',async()=>{const f=fixture();await f.ctx.changeSchoolHubPassword(f.user,'current-password','new-password','new-password');assert.deepEqual(f.calls.map(x=>x[0]),['reauthenticate','token','password']);assert.equal(f.user.uid,'u');});
test('mismatched weak and unchanged passwords fail before any credential request',async()=>{for(const [next,confirm]of [['new-password','wrong'],['123','123'],['current-password','current-password']]){const f=fixture();await assert.rejects(f.ctx.changeSchoolHubPassword(f.user,'current-password',next,confirm));assert.equal(f.calls.length,0);}});
test('incorrect current password never updates password or sends a verification email',async()=>{for(const operation of ['password','email']){const f=fixture();f.user.reauthenticateWithCredential=async()=>{throw Object.assign(Error('wrong'),{code:'auth/wrong-password'});};if(operation==='password')await assert.rejects(f.ctx.changeSchoolHubPassword(f.user,'wrong','new-password','new-password'));else await assert.rejects(f.ctx.requestSchoolHubLoginEmail(f.user,'wrong','new@example.test'));assert.equal(f.calls.length,0);}});
test('new login email is guarded before Firebase sends the verification link',async()=>{const f=fixture();await f.ctx.requestSchoolHubLoginEmail(f.user,'current-password',' NEW@Example.Test ');assert.deepEqual(f.calls.map(x=>x[0]),['reauthenticate','token','call','verify']);assert.equal(f.calls[2][1],'prepareLoginEmailChange');assert.equal(f.calls[3][1],'new@example.test');assert.equal(f.user.email,'old@example.test');assert.equal(f.calls[3][2],'https://school.test/?account-security=1');});
test('duplicate email rejection cannot send verification or change Auth email',async()=>{const f=fixture();f.ctx.safetyCall=async()=>{throw Object.assign(Error('duplicate'),{code:'already-exists'});};await assert.rejects(f.ctx.requestSchoolHubLoginEmail(f.user,'current-password','new@example.test'));assert.equal(f.calls.some(x=>x[0]==='verify'),false);assert.equal(f.user.email,'old@example.test');});
test('Google-only credentials are directed to Google rather than a password change',async()=>{const f=fixture();f.user.providerData=[{providerId:'google.com'}];assert.equal(f.ctx.passwordLoginAvailable(f.user),false);await assert.rejects(f.ctx.changeSchoolHubPassword(f.user,'any','new-password','new-password'),/Google/);assert.equal(f.calls.length,0);});
test('verified email refresh reloads Auth and refreshes token before server reconciliation',async()=>{const f=fixture();await f.ctx.refreshSchoolHubLoginEmail(f.user);assert.deepEqual(f.calls.map(x=>x[0]),['reload','token','call']);assert.equal(f.calls[2][1],'synchronizeLoginEmail');});
test('credential script never writes passwords or credentials to a durable save queue',()=>{assert(!/localStorage|indexedDB|DB\.set|syncDirty|feeQueue/.test(source));assert(source.includes("input[type=\"password\"]"));assert(!source.includes('createUserWithEmailAndPassword'));});
test('qualification choices match Staff schema, new Staff HTML and deployed server copies',()=>{
 const Q=require('../staff-qualifications');const app=fs.readFileSync(path.join(root,'app-4.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
 const ctx={StaffQualifications:Q};vm.createContext(ctx);vm.runInContext(app.slice(app.indexOf('const STAFF_FIELDS ='),app.indexOf('function staffFieldControl('))+'\nglobalThis.fields=STAFF_FIELDS;',ctx);
 for(const [key,values]of Object.entries(Q.choices)){assert.deepEqual(ctx.fields.find(x=>x.key===key).options.map(x=>x[0]),values);const select=html.match(new RegExp('<select id="newStaff_'+key+'">([\\s\\S]*?)</select>'))[1];assert.deepEqual([...select.matchAll(/<option value="([^"]*)"/g)].map(x=>x[1]).filter(Boolean).map(x=>x.replaceAll('&#39;',"'").replaceAll('&amp;','&')),values);}
 assert.equal(fs.readFileSync(path.join(root,'staff-qualifications.js'),'utf8'),fs.readFileSync(path.join(root,'functions/staff-qualifications.js'),'utf8'));
});
test('server-only email rules prevent a verified client from bypassing identity reservations',()=>{const rules=fs.readFileSync(path.join(root,'firestore.rules'),'utf8');const users=rules.slice(rules.indexOf('match /users/{uid}'),rules.indexOf('match /users/{uid}/notifications'));assert(users.includes("hasOnly(['displayName'])"));assert(!users.includes("hasOnly(['displayName', 'email'])"));});
