const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..');
function fixture(options={}){
 const jobs=new Map(),acks=new Map(),calls=[],meta={id:'active',enabled:true,uid:'u',schoolId:'s'};
 const queue={get:async(store,id)=>store==='meta'?{...meta}:jobs.get(id),all:async()=>[...jobs.values()],withLock:async(_,work)=>work(),acknowledge:async(job,error)=>{if(error)jobs.set(job.id,{...job,error});else jobs.delete(job.id);acks.set(job.id,{job,error});}};
 const ctx={console,indexedDB:{},navigator:{locks:{}},clients:{matchAll:async()=>[]},SchoolHubSyncQueue:queue};ctx.self=ctx;
 vm.runInNewContext(fs.readFileSync(path.join(root,'sync-worker.js'),'utf8'),ctx);
 const api={auth:{currentUser:{uid:'u',getIdToken:async()=>{if(options.token)await options.token(meta);}}},db:{collection:()=>({doc:()=>({get:async()=>{if(options.read)await options.read(meta);return {exists:true,data:()=>options.member||{status:'active',schoolId:'s'}};}})})},functions:{httpsCallable:name=>async data=>{calls.push({name,data});if(options.error)throw Object.assign(Error('injected error'),{code:options.error});}}};
 function add(id='a',field='grades',order=0){const j={id,uid:'u',schoolId:'s',lockKey:field==='fees'?'fee-lock':'field-lock',field,kind:'call',name:field==='fees'?'updateSchoolFees':'saveSchoolRecord',data:{requestId:'request-'+id,value:{p:75}},signature:id,order};jobs.set(id,j);return j;}
 return {jobs,acks,calls,meta,api,ctx,add,run:()=>ctx.SchoolHubSyncWorker.run({api})};
}
test('closed PWA uploads through worker with no open windows',async()=>{const f=fixture();f.add();assert.equal(await f.run(),true);assert.equal(f.calls.length,1);assert.equal(f.jobs.size,0);assert.equal(f.acks.size,1);assert.equal(f.calls[0].data.expectedSchoolId,'s');});
test('no matching signed-in session leaves jobs untouched',async()=>{const f=fixture();f.add();f.api.auth.currentUser.uid='other';assert.equal(await f.run(),false);assert.equal(f.calls.length,0);assert.equal(f.jobs.size,1);});
test('sign out disables worker uploads without deleting queued saves',async()=>{const f=fixture();f.add();f.meta.enabled=false;assert.equal(await f.run(),false);assert.equal(f.jobs.size,1);});
test('missing Web Locks falls back instead of racing a window upload',async()=>{const f=fixture();f.add();delete f.ctx.navigator.locks;assert.equal(await f.run(),false);assert.equal(f.jobs.size,1);});
test('revoked membership blocks save and retains a durable error receipt',async()=>{const f=fixture({member:{status:'disabled',schoolId:'s'}});f.add();await f.run();assert.equal(f.calls.length,0);assert(f.jobs.get('a').error);assert(f.acks.get('a').error);});
test('school switch during membership read prevents upload',async()=>{const f=fixture({read:async meta=>{meta.schoolId='other';}});f.add();await f.run();assert.equal(f.calls.length,0);assert.equal(f.jobs.size,1);});
test('logout during token refresh prevents upload',async()=>{const f=fixture({token:async meta=>{meta.enabled=false;}});f.add();await f.run();assert.equal(f.calls.length,0);assert.equal(f.jobs.size,1);});
test('transient failures retain jobs and reject Sync event for browser retry',async()=>{const f=fixture({error:'functions/unavailable'});f.add();await assert.rejects(f.run(),/retried/);assert.equal(f.jobs.size,1);assert.equal(f.acks.size,0);});
test('fee retries preserve the request identifier',async()=>{const f=fixture({error:'functions/unavailable'});const j=f.add('fee','fees');await assert.rejects(f.run());await assert.rejects(f.run());assert.equal(f.calls[0].data.requestId,j.data.requestId);assert.equal(f.calls[1].data.requestId,j.data.requestId);});
test('permanent fee rejection blocks later payments in the same queue',async()=>{const f=fixture({error:'functions/aborted'});f.add('first','fees');f.add('second','fees',1);await f.run();assert.equal(f.calls.length,1);assert(f.jobs.get('first').error);assert(!f.jobs.get('second').error);});
test('already blocked fee prevents later queue items on a later wake',async()=>{const f=fixture();const j=f.add('first','fees');j.error='review required';f.add('second','fees',1);await f.run();assert.equal(f.calls.length,0);});
test('other accounts and schools remain untouched',async()=>{const f=fixture();const j=f.add();j.schoolId='other';assert.equal(await f.run(),true);assert.equal(f.jobs.size,1);assert.equal(f.calls.length,0);});
test('worker budget leaves later jobs queued for another wake',async()=>{const f=fixture();for(let i=0;i<21;i++)f.add('record-'+i,'grades',i);await assert.rejects(f.run(),/retried/);assert.equal(f.calls.length,20);assert.equal(f.jobs.size,1);});
test('edit replaced while waiting for its lock cannot upload stale snapshot',async()=>{const f=fixture();f.add();f.ctx.SchoolHubSyncQueue.withLock=async(_,fn)=>{f.jobs.set('a',{...f.jobs.get('a'),signature:'new'});return fn();};await f.run();assert.equal(f.calls.length,0);assert.equal(f.jobs.get('a').signature,'new');});
test('lost acknowledgement leaves the identical fee request available for safe retry',async()=>{const f=fixture();f.add('fee','fees');const ack=f.ctx.SchoolHubSyncQueue.acknowledge;f.ctx.SchoolHubSyncQueue.acknowledge=async()=>{throw Error('interrupted IndexedDB write');};await assert.rejects(f.run());assert.equal(f.jobs.size,1);f.ctx.SchoolHubSyncQueue.acknowledge=ack;await f.run();assert.equal(f.calls.length,2);assert.equal(f.calls[0].data.requestId,f.calls[1].data.requestId);assert.equal(f.jobs.size,0);});
function clientFixture(current=75){
 const dirty=new Set(['p']),bases=new Map(),removed=[],queue={all:async()=>[{id:'ack',job:{uid:'u',schoolId:'s',lockKey:'lock',field:'grades',rawKey:'key',sentValues:{p:75}},error:''}],remove:async(_,id)=>removed.push(id)};
 const ctx={currentUid:'u',currentSchoolId:'s',SchoolHubSyncQueue:queue,indexedDB:{},document:{addEventListener(){}},window:{addEventListener(){}},syncableFields:()=>[{key:'key',field:'grades'}],DB:{get:()=>({p:current})},fieldDefault:()=>({}),syncBaseValues:bases,dirtyIdsFor:()=>[...dirty],stableSyncJson:JSON.stringify,clearSyncDirty:(_,ids)=>ids.forEach(id=>dirty.delete(id)),syncErrors:new Map()};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'sync-client.js'),'utf8'),ctx);return {ctx,dirty,bases,removed};
}
test('confirmed background snapshot clears its unchanged local dirty record',async()=>{const f=clientFixture();await f.ctx.reconcileWorkerSyncAcks('lock');assert.equal(f.dirty.size,0);assert.equal(f.removed.length,1);});
test('newer local edit survives background receipt and is rebased',async()=>{const f=clientFixture(90);await f.ctx.reconcileWorkerSyncAcks('lock');assert.equal(f.dirty.size,1);assert.equal(f.bases.get('key').p,75);});
test('failed local receipt persistence retains worker acknowledgement',async()=>{const f=clientFixture();f.ctx.clearSyncDirty=()=>{throw Error('storage full');};await assert.rejects(f.ctx.reconcileWorkerSyncAcks('lock'),/storage full/);assert.equal(f.removed.length,0);});
test('old field after account or school change cannot be staged into new workspace',async()=>{const f=clientFixture();Object.assign(f.ctx,{currentStatus:'active',sessionReady:true});f.ctx.SchoolHubSyncQueue.withLock=async(_,fn)=>fn();f.ctx.SchoolHubSyncQueue.fieldLock=x=>x;await f.ctx.stageWorkerField({field:'grades',key:'old-school-key'});assert.equal(f.removed.length,0);});
test('root and hosting copies include identical queue and worker scripts',()=>{for(const file of ['sync-queue.js','sync-worker.js','sync-client.js','firebase-config.js','sw.js','app-4.js','fees.js','index.html','faq.html'])assert.equal(fs.readFileSync(path.join(root,file),'utf8'),fs.readFileSync(path.join(root,'public',file),'utf8'));});
