const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync('app-4.js','utf8');
function section(start,end){const a=source.indexOf(start),b=source.indexOf(end,a+start.length);assert.ok(a>=0&&b>a,`Missing source boundaries: ${start} / ${end}`);return source.slice(a,b);}
function context(code,values={}){return vm.runInContext(code,vm.createContext(values)),values;}
function access(role='teacher'){
 const data={classes:[{id:'a'},{id:'b'}],students:[{id:'one',classId:'a'},{id:'two',classId:'b'},{id:'old',classId:'a',isActive:false}],subjects:[{id:'math'},{id:'art'}]};
 return context(section('function isHeadTeacher()', 'function studentClassIdForYear(')+section('function getAccessibleSubjects()', 'function requireClassAccess('),{currentRole:role,currentStatus:'active',currentAssignedClassIds:['a'],currentAssignedSubjectIds:['math'],isActiveGuest:()=>false,DB:{get:(k,d)=>data[k]??d},KEYS:{classes:'classes',students:'students',subjects:'subjects'},sortSubjectsByOrder:x=>x,alert(){}});
}
test('Head Teacher sees all classes, active students and subjects',()=>{const c=access('headteacher');assert.equal(c.getAccessibleClasses().length,2);assert.equal(c.getAccessibleStudents().length,2);assert.equal(c.getAccessibleSubjects().length,2);assert.equal(c.requireHeadTeacher('edit'),true);});
test('Teacher reads only assigned classes, students and subjects',()=>{const c=access();assert.deepEqual(Array.from(c.getAccessibleStudents(),x=>x.id),['one']);assert.equal(c.getAccessibleClasses().length,1);assert.equal(c.getAccessibleSubjects().length,1);assert.equal(c.canAccessClass('b'),false);assert.equal(c.canAccessSubject('art'),false);assert.equal(c.requireHeadTeacher('edit'),false);assert.equal(c.getAccessibleStudents({includeInactive:true}).length,2);});
test('Missing assignments and inactive identity yield no accessible classes',()=>{const c=access();c.currentAssignedClassIds=null;c.currentAssignedSubjectIds=null;assert.equal(c.getAccessibleStudents().length,0);assert.equal(c.getAccessibleSubjects().length,0);c.currentStatus='disabled';assert.equal(c.requireHeadTeacher('edit'),false);assert.equal(c.canAccessClass('a'),false);});
function navigation(role){
 const c=access(role),nodes=new Map(),calls=[];
 c.document={getElementById:id=>{if(!nodes.has(id))nodes.set(id,{classList:{toggle:(k,v)=>nodes.get(id)[k]=v,add:k=>nodes.get(id)[k]=true}});return nodes.get(id);}};
 Object.assign(c,{FIREBASE_ENABLED:true,sessionReady:true,sessionDataReady:true,enforceGuestTrial:()=>true,saveNavigationState:n=>calls.push(n),sectionTitle:x=>x,window:{scrollTo(){}}});
 for(const name of ['renderHome','refreshHeadTeacherSelect','renderCloudSyncStatus','renderYearRollover','renderYearEndRestorePreview','renderStudentClassSelect','renderAttendanceView','renderGradesClassSelect','renderRemarksClassSelect','renderReportsClassSelect','renderBilling','renderHistoryTermYearSelect','renderManageTeachers','loadActivityLog','renderClasses','renderStudents','renderSubjects','renderStaff','renderFloatingPill','showFloatingPill'])c[name]=()=>calls.push(name);
 vm.runInContext(section('const views =', 'function refreshHeadTeacherSelect('),c);
 return {c,nodes,calls};
}
for(const name of ['home','setup','staff','classes','students','subjects','attendance','grades','remarks','reports','billing','history','manage-teachers','activity'])test(`Head Teacher navigation: ${name}`,()=>{const f=navigation('headteacher');f.c.showView(name);assert.equal(f.nodes.get('view-'+name).hidden,false);assert.equal([...f.nodes].filter(([id,n])=>id.startsWith('view-')&&!n.hidden).length,1);assert.equal(f.calls[0],name);});
for(const name of ['setup','staff','classes','subjects','billing','manage-teachers'])test(`Teacher direct navigation blocks ${name}`,()=>{const f=navigation('teacher');f.c.showView(name);assert.equal(f.nodes.get('view-'+name).hidden,true);assert.equal(f.nodes.get('view-home').hidden,false);assert.equal(f.calls[0],'home');});
for(const name of ['home','students','attendance','grades','remarks','reports'])test(`Teacher navigation permits ${name}`,()=>{const f=navigation('teacher');f.c.showView(name);assert.equal(f.nodes.get('view-'+name).hidden,false);});
test('Navigation cannot render unresolved identity or expose a pre-hydration report view',()=>{const f=navigation('teacher');f.c.sessionReady=false;f.c.showView('reports');assert.equal(f.nodes.size,0);f.c.sessionReady=true;f.c.sessionDataReady=false;f.c.showView('reports');assert.equal(f.nodes.get('view-reports').hidden,true);assert.equal(f.calls.includes('renderReportsClassSelect'),false);});
test('Report asset deadline returns a warning and clears its timer',async()=>{let expire,cleared=0;const c=context(section('async function withReportAssetDeadline(', 'async function checkReportImageAsset('),{setTimeout:fn=>(expire=fn,1),clearTimeout:()=>cleared++});const p=c.withReportAssetDeadline(new Promise(()=>{}),'Photo',100);expire();assert.equal((await p).source,'timeout');assert.equal(cleared,1);assert.equal(await c.withReportAssetDeadline(Promise.resolve('ok'),'Photo'),'ok');assert.equal(cleared,2);await assert.rejects(c.withReportAssetDeadline(Promise.reject(Error('bad')),'Photo'),/bad/);assert.equal(cleared,3);});
test('Report assets prefer record then cache and diagnose missing offline photos',async()=>{let cached=null;const c=context(section('async function checkReportImageAsset(', 'async function mapReportAssetsWithLimit('),{isDataImage:x=>x.startsWith('data:image/'),imageCacheKey:()=> 'photo',getCachedLocalImageAsync:async()=>cached,FIREBASE_ENABLED:false,currentSchoolId:null});const run=value=>c.checkReportImageAsset('student','one',value,'','','','Photo');assert.equal((await run('data:image/png;base64,a')).source,'record');cached='photo';assert.equal((await run('')).source,'local-cache');cached=null;assert.equal((await run('')).ready,false);});
test('Report asset workers preserve order and respect concurrency',async()=>{const c=context(section('async function mapReportAssetsWithLimit(', 'function clearReportAssetCheck('));let active=0,peak=0;const out=await c.mapReportAssetsWithLimit([1,2,3,4,5],2,async x=>{peak=Math.max(peak,++active);await new Promise(r=>setImmediate(r));active--;return x*2;});assert.equal(peak,2);assert.deepEqual(Array.from(out),[2,4,6,8,10]);assert.equal((await c.mapReportAssetsWithLimit([],4,()=>assert.fail())).length,0);});
test('Missing report assets warn before proceeding; complete assets need no confirmation',()=>{let prompts=0;const c=context(section('function reportAssetIssuesForPrepared(', 'async function runReportAction('),{confirm:()=>{prompts++;return false;}});const result={student:{name:'Example'}};assert.equal(c.reportAssetIssuesForPrepared(result,{}).length,3);assert.equal(c.confirmReportAssetIssues(['missing','missing']),false);assert.equal(prompts,1);const issues=c.reportAssetIssuesForPrepared(result,{photo:'p',classTeacherName:'T',classTeacherSignature:'s',headTeacherName:'H',headTeacherSignature:'s'});assert.equal(c.confirmReportAssetIssues(issues),true);assert.equal(prompts,1);});
test('Report asset check denies unassigned class before reading records',async()=>{const wrap={classList:{remove(){}},innerHTML:''};const c=context(section('async function runReportAssetCheck(', 'function reportAssetIssuesForPrepared('),{document:{getElementById:()=>wrap},canAccessClass:()=>false,DB:{get:()=>assert.fail('denied class read')}});assert.equal(await c.runReportAssetCheck('foreign'),null);assert.match(wrap.innerHTML,/class you can access/);});
test('Year-end parser rejects malformed, incomplete and foreign-school backups',()=>{const c=context(section('function parseYearEndBackupFile(', 'function yearEndRestoreCounts('),{currentSchoolId:'school'});const valid={app:'AlatiphA SchoolHub',type:'academic-year-rollover',schoolId:'school',fromYear:'2026/2027',toYear:'2027/2028',data:{students:[],classes:[],settings:{}}};assert.equal(c.parseYearEndBackupFile(JSON.stringify(valid)).schoolId,'school');for(const value of ['{','{}',JSON.stringify({...valid,schoolId:'other'}),JSON.stringify({...valid,toYear:''}),JSON.stringify({...valid,data:{}})])assert.throws(()=>c.parseYearEndBackupFile(value));});
test('Rollover and restore stop immediately for unauthorized users',async()=>{const c=context(section('async function applyYearRollover()', 'const openYearRolloverBtn =')+section('async function applyYearEndEmergencyRestore()', 'const restoreYearEndBackupBtn ='),{yearRolloverDraft:{},pendingYearEndRestore:{},requireHeadTeacher:()=>false});await c.applyYearRollover();await c.applyYearEndEmergencyRestore();});
test('Historical zero scores protect a subject while empty references do not',()=>{const data={classes:[{id:'a',name:'Class A'}],students:[{id:'s',name:'Student'}],grades:{'a__Term 3__2025/2026':{s:{math:{c:0},art:{c:''}}}}};const c=context(section('function subjectGradeRefHasScoreV40(', 'function removeSubjectGradeRefsLocalV40('),{DB:{get:k=>data[k]},KEYS:{classes:'classes',students:'students',grades:'grades'}});assert.equal(c.subjectDepsV40('math').total,1);assert.equal(c.subjectDepsV40('art').total,0);assert.equal(c.subjectDepsV40('unused').total,0);assert.equal(c.subjectGradeReferencesV40(['math'])[0].year,'2025/2026');});
test('Light, dark and system themes update document, browser bar and accessible label',()=>{const attrs={},meta={},button={setAttribute:(k,v)=>button[k]=v};const c=context(section('function applyTheme(', 'function initTheme('),{THEME_ICONS:{light:'L',dark:'D',system:'S'},document:{documentElement:{setAttribute:(k,v)=>attrs[k]=v,removeAttribute:k=>delete attrs[k]},querySelector:()=>({setAttribute:(k,v)=>meta[k]=v}),getElementById:()=>button},window:{matchMedia:()=>({matches:true})}});c.applyTheme('dark');assert.equal(attrs['data-theme'],'dark');assert.equal(meta.content,'#16241C');c.applyTheme('light');assert.equal(meta.content,'#F1EFE6');assert.match(button['aria-label'],/light/);c.applyTheme('system');assert.equal(attrs['data-theme'],undefined);assert.equal(meta.content,'#F1EFE6');});
function worker(){const listeners={},puts=[],deleted=[];const cache={match:async()=>undefined,put:async(...args)=>puts.push(args)};const c=context(fs.readFileSync('sw.js','utf8'),{URL,self:{location:{origin:'https://school.test',href:'https://school.test/sw.js'},addEventListener:(n,fn)=>listeners[n]=fn,skipWaiting:async()=>{},clients:{claim:async()=>{}}},caches:{open:async()=>cache,keys:async()=>[],delete:async k=>deleted.push(k)},fetch:async()=>({ok:true,clone(){return this;}})});return {c,listeners,cache,puts,deleted};}
test('Service worker bypasses writes, school data and untrusted external resources',()=>{const f=worker();for(const [url,method] of [['https://school.test/index.html','POST'],['https://firestore.googleapis.com/v1/data','GET'],['https://school.test/api/students','GET'],['https://other.test/image.png','GET']])f.listeners.fetch({request:{url,method,mode:'cors'},respondWith:()=>assert.fail('private request intercepted')});});
test('Service worker refreshes the shell online and serves cached navigation offline',async()=>{const f=worker(),fresh={ok:true,clone(){return this;}};f.c.fetch=async()=>fresh;assert.equal(await f.c.networkFirst({mode:'navigate'}),fresh);assert.equal(f.puts.length,1);f.c.fetch=async()=>{throw Error('offline');};f.cache.match=async key=>key==='./index.html'?'offline shell':undefined;assert.equal(await f.c.networkFirst({mode:'navigate'}),'offline shell');await assert.rejects(f.c.networkFirst({mode:'cors'}),/offline/);});
test('Failed HTTP responses cannot replace a cached shell',async()=>{const f=worker();f.c.fetch=async()=>({ok:false});f.cache.match=async()=> 'cached';assert.equal(await f.c.networkFirst({mode:'navigate'}),'cached');assert.equal(f.puts.length,0);});
test('Update activation retains current and unrelated caches',async()=>{const f=worker();const current=vm.runInContext('CACHE_NAME',f.c);f.c.caches.keys=async()=>[current,'schoolhub-cache-old','other-cache'];let pending;f.listeners.activate({waitUntil:p=>pending=p});await pending;assert.deepEqual(f.deleted,['schoolhub-cache-old']);});
test('Every shipped public asset matches its root counterpart byte for byte',()=>{function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]);}for(const file of walk('public')){const root=path.relative('public',file);assert.ok(fs.existsSync(root),`Missing root counterpart: ${root}`);assert.deepEqual(fs.readFileSync(file),fs.readFileSync(root),`Parity: ${root}`);}});
test('Every precached shell asset exists in the hosting directory',()=>{const f=worker();for(const url of vm.runInContext('APP_SHELL',f.c)){const relative=url==='./'?'index.html':url.slice(2);assert.ok(fs.existsSync(path.join('public',relative)),`Missing shell asset ${relative}`);}});
function yearGuards(){
 const alerts=[],settings={currentYear:'2026/2027',currentTerm:'Term 3'};
 const c=context(section('async function applyYearRollover()', 'const openYearRolloverBtn =')+section('async function applyYearEndEmergencyRestore()', 'const restoreYearEndBackupBtn ='),{
  yearRolloverDraft:{fromYear:'2026/2027',toYear:'2027/2028',decisions:{}},pendingYearEndRestore:{fromYear:'2025/2026',toYear:'2026/2027',data:{settings:{}}},
  requireHeadTeacher:()=>true,document:{getElementById:()=>null},rolloverCounts:()=>({unresolved:0}),DB:{get:()=>settings,set:()=>assert.fail('unexpected local write')},KEYS:{settings:'settings'},
  confirm:()=>true,alert:x=>alerts.push(x),rolloverStudents:()=>[],FIREBASE_ENABLED:true,currentSchoolId:'school',cloudHydrationInProgress:false,sessionDataReady:true,
  console:{error(){}},rolloverSafeId:x=>x,buildYearEndSnapshot:()=>({}),storeLocalRolloverSnapshot:()=>assert.fail('unexpected snapshot write'),preserveBeforeEmergencyRestore:()=>assert.fail('unexpected snapshot write'),safetyCall:()=>assert.fail('unexpected cloud write')
 });return {c,alerts,settings};
}
for(const reason of ['unresolved','invalid year','stale year','cancelled','hydrating'])test(`Rollover makes no writes when ${reason}`,async()=>{const f=yearGuards();if(reason==='unresolved')f.c.rolloverCounts=()=>({unresolved:1});if(reason==='invalid year')f.c.yearRolloverDraft.toYear='bad';if(reason==='stale year')f.settings.currentYear='2020/2021';if(reason==='cancelled')f.c.confirm=()=>false;if(reason==='hydrating')f.c.cloudHydrationInProgress=true;await f.c.applyYearRollover();assert.equal(f.alerts.length,reason==='cancelled'?0:1);});
for(const reason of ['hydrating','cancelled','snapshot failure'])test(`Emergency restore makes no data writes when ${reason}`,async()=>{const f=yearGuards();if(reason==='hydrating')f.c.sessionDataReady=false;if(reason==='cancelled')f.c.confirm=()=>false;if(reason==='snapshot failure')f.c.preserveBeforeEmergencyRestore=()=>{throw Error('storage full');};await f.c.applyYearEndEmergencyRestore();assert.equal(f.alerts.length,reason==='cancelled'?0:1);if(reason==='snapshot failure')assert.match(f.alerts[0],/storage full/);});
