const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync('live-class-sync.js','utf8'),app=fs.readFileSync('app-4.js','utf8');
function fixture(head=true){
 const subscriptions=[],writes=[],rendered=[],markers=[],listeners={},classes=[];let data=classes,dirty=[],now=0;const notice={textContent:'',classList:{toggle(){}}},form={classList:{contains:()=>true}},home={classList:{contains:()=>true}};
 const c={Date:{now:()=>now},console:{warn(){}},window:{addEventListener:(n,fn)=>listeners[n]=fn},document:{visibilityState:'visible',addEventListener:(n,fn)=>listeners[n]=fn,getElementById:id=>id==='liveClassUpdateStatus'?notice:id==='addClassForm'?form:home},navigator:{onLine:true},FIREBASE_ENABLED:true,currentUid:'u',currentSchoolId:'s',currentStatus:'active',sessionGeneration:1,sessionReady:true,sessionDataReady:true,cloudHydrationInProgress:false,offlineAuthenticatedMode:false,editingClassId:null,isHeadTeacher:()=>head,classIdsForCloudSync:()=>new Set(c.assigned),assigned:['c1'],isCurrentSession:(g,u,s)=>g===c.sessionGeneration&&u===c.currentUid&&s===c.currentSchoolId,
 KEYS:{classes:'classes'},DB:{get:()=>data,set:(key,value,options)=>{assert.equal(options.skipCloudSync,true);data=JSON.parse(JSON.stringify(value));writes.push(data);}},dirtyIdsFor:()=>dirty,localKeyFromCloudId:id=>id,stableSyncJson:JSON.stringify,rememberDeletions:x=>markers.push(...x),backupLocalSchoolData:()=>{},renderClasses:()=>rendered.push(data.map(x=>x.name)),renderHome:()=>{},revalidateAndSyncAfterReconnect:{verifiedContext:{at:1}},setInterval:fn=>c.tick=fn};
 const ref=(p)=>({collection:n=>ref(p+'/'+n),doc:id=>ref(p+'/'+id),where:(field,op,value)=>{assert.equal(field,'collection');assert.equal(op,'==');assert.equal(value,'classes');return ref(p);},onSnapshot:(opts,receive,error)=>{assert.equal(opts.includeMetadataChanges,true);const s={p,receive,error,stopped:false};subscriptions.push(s);return ()=>{s.stopped=true;};}});c.schoolRef=()=>ref('schools/'+c.currentSchoolId);
 vm.createContext(c);vm.runInContext(app.slice(app.indexOf('function mergeRecordsById('),app.indexOf('function mergeKeyedData(')),c);vm.runInContext(code,c);
 const emit=(path,docs,metadata={fromCache:false,hasPendingWrites:false})=>{const snapshot={metadata,forEach:fn=>docs.forEach(x=>fn({id:x.id,data:()=>x})),exists:docs.length>0,data:()=>docs[0]};subscriptions.filter(s=>s.p==='schools/s/'+path&&!s.stopped).forEach(s=>s.receive(snapshot));};
 return {c,subscriptions,writes,rendered,markers,notice,form,emit,get:()=>data,set:value=>data=value,dirty:value=>dirty=value,clock:value=>now=value,listeners};
}
const cls=(id,name)=>({id,name,classTeacherId:''});
test('two open clients receive class additions and renames without refresh',()=>{const a=fixture(),b=fixture();for(const f of [a,b]){f.emit('deletedRecords',[]);f.emit('classes',[cls('c1','Sync test')]);assert.equal(f.get()[0].name,'Sync test');f.emit('classes',[cls('c1','Phone rename')]);assert.equal(f.get()[0].name,'Phone rename');assert.deepEqual(f.rendered.at(-1),['Phone rename']);}});
test('confirmed deletion reaches both clients only after record absence and marker agree',()=>{for(const f of [fixture(),fixture()]){f.emit('deletedRecords',[]);f.emit('classes',[cls('c1','Test')]);f.emit('deletedRecords',[{id:'c1',collection:'classes',version:'v1'}]);assert.equal(f.get().length,1);f.emit('classes',[]);assert.equal(f.get().length,0);assert.equal(f.markers.at(-1).version,'v1');}});
test('cloud absence alone never removes local records',()=>{const f=fixture();f.set([cls('local','Recovery')]);f.emit('deletedRecords',[]);f.emit('classes',[]);assert.equal(f.get()[0].name,'Recovery');});
test('pending local edits win over remote rename and deletion',()=>{const f=fixture();f.set([cls('c1','Offline local edit')]);f.dirty(['c1']);f.emit('deletedRecords',[{id:'c1',collection:'classes',version:'gone'}]);f.emit('classes',[cls('c1','Cloud rename')]);assert.equal(f.get()[0].name,'Offline local edit');f.emit('classes',[]);assert.equal(f.get().length,1);assert.equal(f.markers.length,0);});
test('editing forms retain their input and baseline until closed',()=>{const f=fixture();f.set([cls('c1','Original')]);f.c.editingClassId='c1';f.emit('deletedRecords',[]);f.emit('classes',[cls('c1','Remote change')]);assert.equal(f.get()[0].name,'Original');assert.equal(f.rendered.length,0);assert.match(f.notice.textContent,/Finish or close/);f.c.editingClassId=null;f.c.tick();assert.equal(f.get()[0].name,'Remote change');assert.equal(f.rendered.length,1);});
test('Add Class form is preserved and unchanged data does not show a false update notice',()=>{const f=fixture();f.form.classList.contains=()=>false;f.set([cls('c1','Original')]);f.emit('deletedRecords',[]);f.emit('classes',[cls('c1','Original')]);assert.equal(f.notice.textContent,'');f.emit('classes',[cls('c1','Changed')]);assert.equal(f.get()[0].name,'Original');assert.match(f.notice.textContent,/Finish or close/);});
test('cache and pending-write snapshots cannot remove or replace records',()=>{const f=fixture();f.set([cls('c1','Original')]);f.emit('deletedRecords',[]);for(const metadata of [{fromCache:true,hasPendingWrites:false},{fromCache:false,hasPendingWrites:true}])f.emit('classes',[cls('c1','Stale')],metadata);assert.equal(f.writes.length,0);f.emit('classes',[cls('c1','Server')]);assert.equal(f.get()[0].name,'Server');});
test('teacher listeners are restricted to assigned class documents and markers are scoped',()=>{const f=fixture(false);assert(!f.subscriptions.some(s=>s.p==='schools/s/classes'));assert(f.subscriptions.some(s=>s.p==='schools/s/classes/c1'));f.set([cls('c2','Unassigned recovery')]);f.emit('deletedRecords',[{id:'c2',collection:'classes',version:'v2'}]);f.emit('classes/c1',[cls('c1','Assigned')]);assert.equal(f.get().length,2);assert.equal(f.markers.length,0);});
test('late callbacks after account or assignment switch cannot mutate new workspace',()=>{const f=fixture(false),old=f.subscriptions.find(s=>s.p.endsWith('/c1'));f.c.currentUid='other';old.receive({metadata:{fromCache:false},exists:true,data:()=>cls('c1','Old user')});assert.equal(f.writes.length,0);f.c.tick();assert(f.subscriptions.slice(0,2).every(s=>s.stopped));});
test('hidden/offline pages stop listeners and visible verified pages attach again',()=>{const f=fixture();f.c.document.visibilityState='hidden';f.listeners.visibilitychange();assert(f.subscriptions.every(s=>s.stopped));const count=f.subscriptions.length;f.c.tick();assert.equal(f.subscriptions.length,count);f.c.document.visibilityState='visible';f.c.offlineAuthenticatedMode=true;f.listeners.visibilitychange();assert.equal(f.subscriptions.length,count);f.c.offlineAuthenticatedMode=false;f.c.tick();assert(f.subscriptions.length>count);});
test('listener errors retry after backoff; denied access waits for fresh verification',()=>{const f=fixture();f.subscriptions[0].error({code:'unavailable'});const n=f.subscriptions.length;f.c.tick();assert.equal(f.subscriptions.length,n);f.clock(10000);f.c.tick();assert(f.subscriptions.length>n);f.subscriptions.at(-1).error({code:'permission-denied'});const denied=f.subscriptions.length;f.clock(60000);f.c.tick();assert.equal(f.subscriptions.length,denied);f.c.revalidateAndSyncAfterReconnect.verifiedContext.at=2;f.c.tick();assert(f.subscriptions.length>denied);});
test('healthy subscription does not issue repeated network reads',()=>{const f=fixture(),count=f.subscriptions.length;for(let i=0;i<30;i++)f.c.tick();assert.equal(f.subscriptions.length,count);});
