const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync('live-student-sync.js','utf8');
const app=fs.readFileSync('app-4.js','utf8');
const storageHelpers=app.slice(app.indexOf('function stripImagesForLocalStorage('),app.indexOf('function openImageDB()',app.indexOf('function stripImagesForLocalStorage(')));
function fixture(head=true,assigned=['c1'],persistLikeProduction=false){
 let data=[],dirty=[],now=0;const subscriptions=[],writes=[],renders=[],remembered=[],events={};
 const element=hidden=>({value:'',textContent:'',hidden,classList:{contains(){return this.el.hidden;},toggle(_,v){this.el.hidden=v;}}});
 const els=Object.fromEntries(['liveStudentUpdateStatus','addStudentForm','addClassForm','view-home','view-classes','view-students','bulkStudentInput'].map(id=>[id,element(id!=='view-students')]));
 for(const el of Object.values(els))el.classList.el=el;
 const c={Date:{now:()=>now},console:{warn(){}},window:{addEventListener:(n,f)=>events[n]=f},document:{visibilityState:'visible',addEventListener:(n,f)=>events[n]=f,getElementById:id=>els[id]||null},navigator:{onLine:true},FIREBASE_ENABLED:true,currentUid:'u',currentSchoolId:'s',currentStatus:'active',sessionGeneration:1,sessionReady:true,sessionDataReady:true,cloudHydrationInProgress:false,offlineAuthenticatedMode:false,editingStudentId:null,editingClassId:null,assigned,isHeadTeacher:()=>head,classIdsForCloudSync:()=>new Set(c.assigned),isCurrentSession:(g,u,s)=>g===c.sessionGeneration&&u===c.currentUid&&s===c.currentSchoolId,KEYS:{students:'students'},DB:{get:()=>data,set:(k,v,o)=>{assert.equal(k,'students');assert.equal(o.skipCloudSync,true);data=structuredClone(v);writes.push(data);}},dirtyIdsFor:()=>dirty,localKeyFromCloudId:id=>id,stableSyncJson:JSON.stringify,rememberDeletions:x=>remembered.push(...x),backupLocalSchoolData:()=>true,mergeRecordsById:(a,b)=>[...new Map([...a,...b].map(x=>[x.id,x])).values()],mergeLocalImage:(_,r,id)=>({...r,photo:data.find(x=>x.id===id)?.photo||''}),renderStudents:()=>renders.push(data.map(x=>x.name)),renderHome:()=>{},renderClasses:()=>{},revalidateAndSyncAfterReconnect:{verifiedContext:{at:1}},setInterval:f=>c.tick=f};
 const ref=p=>({collection:n=>ref(p+'/'+n),where:(f,o,v)=>{assert.equal(o,'==');assert(['classId','collection'].includes(f));return ref(p+'?'+f+'='+v);},onSnapshot:(opts,receive,error)=>{assert.equal(opts.includeMetadataChanges,true);const s={p,receive,error,stopped:false};subscriptions.push(s);return()=>s.stopped=true;}});c.schoolRef=()=>ref('schools/'+c.currentSchoolId);
 c.imageMemoryCache=new Map();c.imageCacheKey=(kind,id)=>kind+':'+id;
 vm.createContext(c);vm.runInContext(storageHelpers,c);
 if(persistLikeProduction){c.DB.get=k=>c.restoreLocalImagesForDbKey(k,JSON.parse(JSON.stringify(data)));c.DB.set=(k,v,o)=>{assert.equal(o.skipCloudSync,true);data=JSON.parse(JSON.stringify(c.stripImagesForLocalStorage(k,v)));writes.push(data);};}
 vm.runInContext(code,c);
 const emit=(path,records,metadata={fromCache:false,hasPendingWrites:false},changes=[])=>subscriptions.filter(s=>s.p==='schools/s/'+path&&!s.stopped).forEach(s=>s.receive({metadata,forEach:f=>records.forEach(r=>f({id:r.id,data:()=>r})),docChanges:()=>changes.map(x=>({type:x.type,doc:{id:x.id,data:()=>x}}))}));
 return {c,els,subscriptions,writes,renders,remembered,events,emit,set:x=>data=x,get:()=>data,dirty:x=>dirty=x,clock:x=>now=x};
}
const pupil=(id,name,classId='c1')=>({id,name,classId});
const markers=f=>f.emit('deletedRecords?collection=students',[]);
test('two active clients receive additions and subsequent renames without a full pull',()=>{for(const f of [fixture(),fixture()]){f.set([pupil('original','Existing')]);markers(f);f.emit('students',[pupil('original','Existing'),pupil('test','Pilot')]);assert.equal(f.get().length,2);f.emit('students',[pupil('original','Existing'),pupil('test','Renamed')]);assert.equal(f.get()[1].name,'Renamed');assert.deepEqual(f.renders.at(-1),['Existing','Renamed']);}});
test('teacher listens only to assigned class queries and rejects foreign-class records',()=>{const f=fixture(false);assert(f.subscriptions.some(s=>s.p.endsWith('students?classId=c1')));assert(!f.subscriptions.some(s=>s.p.endsWith('/students')));markers(f);f.emit('students?classId=c1',[pupil('ok','Assigned'),pupil('foreign','Other','c2')]);assert.deepEqual(f.get().map(x=>x.id),['ok']);});
test('one assigned class update is not held behind another class query; existing pupils remain',()=>{const f=fixture(false,['c1','c2']);f.set([pupil('b','Existing','c2')]);markers(f);f.emit('students?classId=c1',[pupil('a','First')]);assert.equal(f.get().length,2);f.emit('students?classId=c2',[pupil('b','Second','c2')]);assert.equal(f.get().length,2);assert.equal(f.get().find(x=>x.id==='b').name,'Second');});

test('teacher receives confirmed additions and renames even when deletion history is delayed',()=>{const f=fixture(false);f.set([pupil('original','Existing')]);f.emit('students?classId=c1',[pupil('original','Existing'),pupil('test','Pilot')]);assert.equal(f.get().length,2);f.emit('students?classId=c1',[pupil('original','Existing'),pupil('test','Renamed')]);assert.equal(f.get().find(x=>x.id==='test').name,'Renamed');assert.deepEqual(f.renders.at(-1),['Existing','Renamed']);assert.match(f.els.liveStudentUpdateStatus.textContent,/connected/);});

test('partial assigned query results cannot apply deletion markers until all classes confirm',()=>{const f=fixture(false,['c1','c2']);f.set([pupil('p','Existing','c2')]);f.emit('deletedRecords?collection=students',[{id:'p',collection:'students',version:'v'}]);f.emit('students?classId=c1',[]);assert.equal(f.get().length,1);f.emit('students?classId=c2',[pupil('p','Still exists','c2')]);assert.equal(f.get().length,1);f.emit('students?classId=c2',[]);assert.equal(f.get().length,0);});
test('cache and locally pending snapshots never replace confirmed records',()=>{const f=fixture();f.set([pupil('p','Original')]);markers(f);for(const metadata of [{fromCache:true},{hasPendingWrites:true}])f.emit('students',[pupil('p','Stale')],metadata);assert.equal(f.writes.length,0);f.emit('students',[pupil('p','Server')]);assert.equal(f.get()[0].name,'Server');});
test('pending offline edits win over remote changes and deletion markers',()=>{const f=fixture();f.set([pupil('p','Pending')]);f.dirty(['p']);f.emit('deletedRecords?collection=students',[{id:'p',collection:'students',version:'v'}]);f.emit('students',[pupil('p','Remote')]);assert.equal(f.get()[0].name,'Pending');f.emit('students',[]);assert.equal(f.get()[0].name,'Pending');assert.equal(f.remembered.length,0);});
test('cloud absence alone retains recovery records; confirmed tombstones remove only absent clean records',()=>{const f=fixture();f.set([pupil('local','Recovery'),pupil('p','Remove')]);markers(f);f.emit('students',[]);assert.equal(f.get().length,2);f.emit('deletedRecords?collection=students',[{id:'p',collection:'students',version:'v'}]);assert.deepEqual(f.get().map(x=>x.id),['local']);assert.equal(f.remembered[0].version,'v');});
test('remote edit changes the baseline but never replaces an open editor; closing renders buffered data',()=>{const f=fixture();f.set([pupil('p','Original')]);f.c.editingStudentId='p';markers(f);f.emit('students',[pupil('p','Remote')]);assert.equal(f.get()[0].name,'Remote');assert.equal(f.renders.length,0);assert.match(f.els.liveStudentUpdateStatus.textContent,/Finish or close/);f.c.editingStudentId=null;f.c.tick();assert.equal(f.renders.length,1);});
test('Add Student and bulk entry forms keep their nodes while data updates',()=>{for(const bulk of [false,true]){const f=fixture();if(bulk)f.els.bulkStudentInput.value='Unsaved entry';else f.els.addStudentForm.hidden=false;markers(f);f.emit('students',[pupil('p','New')]);assert.equal(f.get().length,1);assert.equal(f.renders.length,0);if(bulk)assert.equal(f.els.bulkStudentInput.value,'Unsaved entry');f.els.bulkStudentInput.value='';f.els.addStudentForm.hidden=true;f.c.tick();assert.equal(f.renders.length,1);}});
test('cached photos remain attached to incoming pupil metadata',()=>{const f=fixture();f.set([{...pupil('p','Old'),photo:'data:image/png;base64,synthetic'}]);markers(f);f.emit('students',[pupil('p','New')]);assert.equal(f.get()[0].photo,'data:image/png;base64,synthetic');});
test('callbacks from previous user, school or assignments cannot write into the current workspace',()=>{for(const mutation of [f=>f.c.currentUid='other',f=>f.c.currentSchoolId='other',f=>f.c.assigned=['c2']]){const f=fixture(false),old=f.subscriptions.find(s=>s.p.includes('students?'));mutation(f);old.receive({metadata:{},forEach:fn=>fn({id:'p',data:()=>pupil('p','Late')})});assert.equal(f.writes.length,0);f.c.tick();assert(old.stopped);}});
test('hidden/offline/unverified sessions detach listeners and cannot receive changes',()=>{const f=fixture();f.c.document.visibilityState='hidden';f.events.visibilitychange();assert(f.subscriptions.every(x=>x.stopped));const count=f.subscriptions.length;f.c.document.visibilityState='visible';f.c.offlineAuthenticatedMode=true;f.events.visibilitychange();assert.equal(f.subscriptions.length,count);f.c.offlineAuthenticatedMode=false;f.c.tick();assert(f.subscriptions.length>count);});
test('permission errors require fresh account verification and transient errors back off',()=>{const f=fixture();f.subscriptions[0].error({code:'unavailable'});const n=f.subscriptions.length;f.c.tick();assert.equal(f.subscriptions.length,n);f.clock(10000);f.c.tick();assert(f.subscriptions.length>n);f.subscriptions.at(-1).error({code:'permission-denied'});const denied=f.subscriptions.length;f.clock(60000);f.c.tick();assert.equal(f.subscriptions.length,denied);f.c.revalidateAndSyncAfterReconnect.verifiedContext.at=2;f.c.tick();assert(f.subscriptions.length>denied);});
test('healthy listeners do not repeatedly read the whole school',()=>{const f=fixture(),n=f.subscriptions.length;for(let i=0;i<30;i++)f.c.tick();assert.equal(f.subscriptions.length,n);});

test('real storage normalization prevents idle redraws for pupils without photos',()=>{const f=fixture(false,['c1'],true);f.set([pupil('p','Existing')]);markers(f);f.emit('students?classId=c1',[pupil('p','Existing')]);assert.equal(f.writes.length,0);assert.equal(f.renders.length,0);for(let i=0;i<30;i++)f.c.tick();assert.equal(f.writes.length,0);assert.equal(f.renders.length,0);f.emit('students?classId=c1',[pupil('p','Renamed')]);assert.equal(f.writes.length,1);assert.equal(f.renders.length,1);for(let i=0;i<30;i++)f.c.tick();assert.equal(f.writes.length,1);assert.equal(f.renders.length,1);});

test('cached photo restoration remains visible without causing repeated storage writes',()=>{const f=fixture(false,['c1'],true);f.set([pupil('p','Existing')]);f.c.imageMemoryCache.set('student:p','data:image/png;base64,synthetic');markers(f);f.emit('students?classId=c1',[pupil('p','Renamed')]);assert.equal(f.writes.length,1);for(let i=0;i<30;i++)f.c.tick();assert.equal(f.writes.length,1);assert.equal(f.renders.length,1);assert.equal(f.c.DB.get('students')[0].photo,'data:image/png;base64,synthetic');});
test('an explicitly confirmed move outside teacher scope hides a previously observed clean pupil',()=>{const f=fixture(false);markers(f);f.emit('students?classId=c1',[pupil('p','Assigned')]);f.emit('students?classId=c1',[],undefined,[{...pupil('p','Moved','c2'),type:'removed'}]);assert.equal(f.get().length,0);});
test('failed recovery checkpoint leaves local pupil data untouched',()=>{const f=fixture();f.set([pupil('p','Original')]);f.c.backupLocalSchoolData=()=>false;markers(f);f.emit('students',[pupil('p','Remote')]);assert.equal(f.get()[0].name,'Original');assert.equal(f.writes.length,0);});
