const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function fixture(){
 let receive,reads=0,writes=0,unsubs=0,dirty=[],store={other:{preserved:true}},timer;
 const cells=[{dataset:{student:'pupil',subject:'English',part:'c'},value:''},{dataset:{student:'pupil',subject:'English',part:'e'},value:''}];
 const notice={textContent:'',classList:{toggle(){}}},view={classList:{contains(){return false;}}},select={value:'class4'},events={};
 const ctx={console,Map,Set,JSON,Date,String,Array,Object,Number,FIREBASE_ENABLED:true,currentUid:'teacher',currentSchoolId:'school',currentStatus:'active',sessionGeneration:1,sessionReady:true,sessionDataReady:true,cloudHydrationInProgress:false,offlineAuthenticatedMode:false,navigator:{onLine:true},KEYS:{grades:'grades',settings:'settings'},isHeadTeacher:()=>false,classIdsForCloudSync:()=>['class4'],canAccessClass:id=>id==='class4',gradeKey:(id,t,y)=>`${id}__${t}__${y}`,revalidateAndSyncAfterReconnect:{},isCurrentSession:(g,u,s)=>g===ctx.sessionGeneration&&u===ctx.currentUid&&s===ctx.currentSchoolId,stableSyncJson:JSON.stringify,dirtyIdsFor:()=>dirty,backupLocalSchoolData:()=>true,DB:{get:key=>key==='settings'?{currentTerm:'Term 1',currentYear:'2026/2027'}:store,set:(key,value,options)=>{assert.equal(options.skipCloudSync,true);store=value;writes++;}},gradeRef:key=>({onSnapshot(options,cb){assert.equal(options.includeMetadataChanges,true);reads++;receive=cb;return()=>unsubs++;}}),document:{visibilityState:'visible',getElementById:id=>id==='view-grades'?view:id==='gradesClassSelect'?select:notice,querySelectorAll:()=>cells,addEventListener:(type,fn)=>events[type]=fn},setInterval:fn=>timer=fn,alert:()=>{}};
 ctx.window=ctx;ctx.addEventListener=(type,fn)=>events[type]=fn;
 vm.createContext(ctx);vm.runInContext(fs.readFileSync('live-grade-sync.js','utf8'),ctx);
 return {ctx,cells,notice,select,events,get store(){return store;},get reads(){return reads;},get writes(){return writes;},get unsubs(){return unsubs;},setDirty:v=>dirty=v,tick:()=>timer(),send:(entries,metadata={},exists=true)=>receive({metadata,exists,data:()=>({entries})})};
}
const entries=(c=5,e=10)=>({pupil:{English:{c,e}}});
test('confirmed grades update existing cells and retain other class records',()=>{const f=fixture(),node=f.cells[0];f.send(entries());assert.equal(f.cells[0],node);assert.equal(node.value,'5');assert.equal(f.cells[1].value,'10');assert.deepEqual(f.store.other,{preserved:true});assert.equal(f.writes,1);});
test('unchanged snapshots and healthy timer do not redraw, write or reattach',()=>{const f=fixture();f.send(entries());f.send(entries());f.tick();f.tick();assert.equal(f.writes,1);assert.equal(f.reads,1);});
test('cached, locally pending and missing document snapshots cannot erase saved grades',()=>{const f=fixture();f.send(entries());f.send(entries(0,0),{fromCache:true});f.send(entries(0,0),{hasPendingWrites:true});f.send({}, {},false);assert.equal(f.cells[0].value,'5');assert.equal(f.writes,1);});
test('local pending class grades win until acknowledged server update arrives',()=>{const f=fixture();f.setDirty(['class4__Term 1__2026/2027']);f.send(entries());assert.equal(f.writes,0);f.setDirty([]);f.send(entries());assert.equal(f.cells[0].value,'5');});
test('unfinished score stays while unrelated remote score updates',()=>{const f=fixture();f.cells[0].value='7';f.send(entries('',10));assert.equal(f.cells[0].value,'7');assert.equal(f.cells[1].value,'10');assert.equal(f.ctx.canSaveLiveGrades(),true);});
test('same-cell conflict blocks save and remains blocked across repeated snapshots',()=>{const f=fixture();f.cells[0].value='7';f.send(entries());assert.equal(f.ctx.canSaveLiveGrades(),false);f.send(entries());assert.equal(f.ctx.canSaveLiveGrades(),false);f.cells[0].value='5';assert.equal(f.ctx.canSaveLiveGrades(),true);});
test('callbacks from former account and class scope are ignored',()=>{const f=fixture();f.ctx.currentUid='other';f.send(entries());assert.equal(f.writes,0);f.tick();assert.equal(f.unsubs,1);});
test('offline, unverified, and unassigned grade contexts do not attach',()=>{for(const change of [f=>f.ctx.navigator.onLine=false,f=>f.ctx.offlineAuthenticatedMode=true,f=>f.select.value='class5']){const f=fixture();change(f);f.tick();const reads=f.reads;f.tick();f.send(entries());assert.equal(f.reads,reads);assert.equal(f.writes,0);}});

test('routine account recovery keeps unfinished conflicted cell and its save block',()=>{const f=fixture();f.send(entries(5));f.cells[0].value='6';f.send(entries(7));f.ctx.offlineAuthenticatedMode=true;f.tick();f.ctx.offlineAuthenticatedMode=false;assert.equal(f.ctx.preserveLiveGradeSheetAfterRecovery(),true);assert.equal(f.cells[0].value,'6');assert.equal(f.ctx.canSaveLiveGrades(),false);f.send(entries(7));assert.equal(f.cells[0].value,'6');assert.equal(f.ctx.canSaveLiveGrades(),false);});
test('account, class, term and assignment changes cannot preserve an old sheet',()=>{for(const change of [f=>f.ctx.currentUid='other',f=>f.ctx.sessionGeneration++,f=>f.select.value='class5',f=>f.ctx.currentAssignedSubjectIds=['new-subject'],f=>f.ctx.DB.get=key=>key==='settings'?{currentTerm:'Term 2',currentYear:'2026/2027'}:{}]){const f=fixture();change(f);assert.equal(f.ctx.preserveLiveGradeSheetAfterRecovery(),false);}});
test('explicit grade-sheet reopening resets conflict baseline to the saved score',()=>{const f=fixture();f.send(entries(5));f.cells[0].value='6';f.send(entries(7));assert.equal(f.ctx.canSaveLiveGrades(),false);f.cells[0].value='7';f.ctx.captureLiveGradeBaseline();assert.equal(f.ctx.canSaveLiveGrades(),true);});
