const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function fixture(){
 let receive,reads=0,writes=0,unsubs=0,dirty=[],store={other:{preserved:true}},timer;
 const cells=[{dataset:{student:'pupil'},value:''},{dataset:{student:'otherPupil'},value:''}];
 const notice={textContent:'',classList:{toggle(){}}},view={classList:{contains(){return false;}}},select={value:'class4'},events={};
 const ctx={console,Map,Set,JSON,Date,String,Array,Object,Number,FIREBASE_ENABLED:true,currentUid:'teacher',currentSchoolId:'school',currentStatus:'active',sessionGeneration:1,sessionReady:true,sessionDataReady:true,cloudHydrationInProgress:false,offlineAuthenticatedMode:false,navigator:{onLine:true},KEYS:{attendance:'attendance',settings:'settings'},isHeadTeacher:()=>false,classIdsForCloudSync:()=>['class4'],canAccessClass:id=>id==='class4',attendanceKey:(id,t,y,date)=>`${id}__${t}__${y}__${date}`,revalidateAndSyncAfterReconnect:{},isCurrentSession:(g,u,s)=>g===ctx.sessionGeneration&&u===ctx.currentUid&&s===ctx.currentSchoolId,stableSyncJson:JSON.stringify,dirtyIdsFor:()=>dirty,backupLocalSchoolData:()=>true,DB:{get:key=>key==='settings'?{currentTerm:'Term 1',currentYear:'2026/2027'}:store,set:(key,value,options)=>{assert.equal(options.skipCloudSync,true);store=value;writes++;}},attendanceRef:key=>({onSnapshot(options,cb){assert.equal(options.includeMetadataChanges,true);reads++;receive=cb;return()=>unsubs++;}}),document:{visibilityState:'visible',getElementById:id=>id==='view-attendance'||id==='studentAttendancePanel'?view:id==='attendanceClassSelect'?select:id==='attendanceDate'?{value:'2026-10-07'}:notice,querySelectorAll:()=>cells,addEventListener:(type,fn)=>events[type]=fn},setInterval:fn=>timer=fn,alert:()=>{}};
 ctx.window=ctx;ctx.addEventListener=(type,fn)=>events[type]=fn;
 vm.createContext(ctx);vm.runInContext(fs.readFileSync('live-attendance-sync.js','utf8'),ctx);
 return {ctx,cells,notice,select,events,get store(){return store;},get reads(){return reads;},get writes(){return writes;},get unsubs(){return unsubs;},setDirty:v=>dirty=v,tick:()=>timer(),send:(entries,metadata={},exists=true)=>receive({metadata,exists,data:()=>({entries})})};
}
const entries=(c='P',e='A')=>({pupil:c,otherPupil:e});
test('confirmed attendance update existing cells and retain other class records',()=>{const f=fixture(),node=f.cells[0];f.send(entries());assert.equal(f.cells[0],node);assert.equal(node.value,'P');assert.equal(f.cells[1].value,'A');assert.deepEqual(f.store.other,{preserved:true});assert.equal(f.writes,1);});
test('unchanged snapshots and healthy timer do not redraw, write or reattach',()=>{const f=fixture();f.send(entries());f.send(entries());f.tick();f.tick();assert.equal(f.writes,1);assert.equal(f.reads,1);});
test('cached, locally pending and missing document snapshots cannot erase saved attendance',()=>{const f=fixture();f.send(entries());f.send(entries(0,0),{fromCache:true});f.send(entries(0,0),{hasPendingWrites:true});f.send({}, {},false);assert.equal(f.cells[0].value,'P');assert.equal(f.writes,1);});
test('local pending class attendance win until acknowledged server update arrives',()=>{const f=fixture();f.setDirty(['class4__Term 1__2026/2027__2026-10-07']);f.send(entries());assert.equal(f.writes,0);f.setDirty([]);f.send(entries());assert.equal(f.cells[0].value,'P');});
test('unfinished status stays while unrelated remote status updates',()=>{const f=fixture();f.cells[0].value='L';f.send(entries('','A'));assert.equal(f.cells[0].value,'L');assert.equal(f.cells[1].value,'A');assert.equal(f.ctx.canSaveLiveAttendance(),true);});
test('same-cell conflict blocks save and remains blocked across repeated snapshots',()=>{const f=fixture();f.cells[0].value='L';f.send(entries());assert.equal(f.ctx.canSaveLiveAttendance(),false);f.send(entries());assert.equal(f.ctx.canSaveLiveAttendance(),false);f.cells[0].value='P';assert.equal(f.ctx.canSaveLiveAttendance(),true);});
test('callbacks from former account and class scope are ignored',()=>{const f=fixture();f.ctx.currentUid='other';f.send(entries());assert.equal(f.writes,0);f.tick();assert.equal(f.unsubs,1);});
test('offline, unverified, and unassigned grade contexts do not attach',()=>{for(const change of [f=>f.ctx.navigator.onLine=false,f=>f.ctx.offlineAuthenticatedMode=true,f=>f.select.value='class5']){const f=fixture();change(f);f.tick();const reads=f.reads;f.tick();f.send(entries());assert.equal(f.reads,reads);assert.equal(f.writes,0);}});
