const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),{webcrypto}=require('crypto');
const moduleSource=fs.readFileSync('offline-drafts.js','utf8'),ops=fs.readFileSync('school-operations.js','utf8');
function fixture(storage=new Map()){const c={Date,crypto:webcrypto,window:{},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}};vm.createContext(c);vm.runInContext(moduleSource,c);return{c,api:c.window.SchoolHubDrafts,storage};}
test('four independent stock drafts survive restart and editing one preserves the other three',()=>{const f=fixture(),ids=[];for(let i=0;i<4;i++)ids.push(f.api.saveStock('u','s',null,{itemId:'item-'+i,quantityMilli:String(i+1),purpose:'Purpose '+i}).id);const reopened=fixture(f.storage);assert.equal(reopened.api.listStock('u','s').length,4);reopened.api.saveStock('u','s',ids[1],{itemId:'item-1',quantityMilli:'3.125',purpose:'Updated'});const list=reopened.api.listStock('u','s');assert.equal(list[1].id,ids[1]);assert.equal(list[1].values.quantityMilli,'3.125');assert.equal(list[0].values.purpose,'Purpose 0');assert.equal(list[3].values.purpose,'Purpose 3');assert.equal(new Set(ids).size,4);});
test('discard or confirmed submission removes only its selected draft',()=>{const f=fixture(),a=f.api.saveStock('u','s',null,{itemId:'a'}),b=f.api.saveStock('u','s',null,{itemId:'b'});f.api.removeStock('u','s',a.id);assert.equal(f.api.listStock('u','s').length,1);assert.equal(f.api.listStock('u','s')[0].id,b.id);});
test('existing single draft migrates without changing its raw quantity or destroying it on read',()=>{const f=fixture();f.api.write('stock-request','u','s',{values:{itemId:'old',quantityMilli:'2.125',purpose:'Existing'}});const original=[...f.storage.values()][0];assert.equal(f.api.listStock('u','s')[0].values.quantityMilli,'2.125');assert.equal([...f.storage.values()][0],original);f.api.saveStock('u','s',null,{itemId:'new'});assert.equal(f.api.listStock('u','s').length,2);assert.equal(f.api.listStock('u','s')[0].values.purpose,'Existing');assert.throws(()=>f.api.write('stock-request','u','s',{values:{itemId:'overwrite'}}));assert.equal(f.api.listStock('u','s').length,2);});
test('multi-drafts retain account/school isolation and never store credentials or extra server fields',()=>{const f=fixture();f.api.saveStock('u','s',null,{itemId:'a',quantityMilli:'1',purpose:'Test',password:'SECRET',role:'headteacher',requestId:'injected'});assert.equal(f.api.listStock('v','s').length,0);assert.equal(f.api.listStock('u','other').length,0);assert.equal(f.api.read('my-details','u','s'),null);assert(![...f.storage.values()].join('').includes('SECRET'));assert(!f.api.listStock('u','s')[0].values.requestId);});
test('quota or corrupt collection errors preserve existing drafts without falling back to empty data',()=>{const f=fixture();f.api.saveStock('u','s',null,{itemId:'a'});const key=[...f.storage.keys()][0],before=f.storage.get(key);f.c.localStorage.setItem=()=>{throw Error('quota')};assert.throws(()=>f.api.saveStock('u','s',null,{itemId:'b'}),/quota/);assert.equal(f.storage.get(key),before);f.storage.set(key,'{"version":2,"drafts":"bad"}');assert.throws(()=>f.api.listStock('u','s'),/recovery/);assert.throws(()=>f.api.removeStock('u','s','a'),/recovery/);});
function operationsFixture(){const f=fixture(),c=f.c;c.console=console;c.currentUid='u';c.currentSchoolId='s';c.currentStatus='active';c.sessionGeneration=1;c.sessionReady=true;c.sessionDataReady=true;c.offlineAuthenticatedMode=false;c.navigator={onLine:true};c.isHeadTeacher=()=>false;c.FIREBASE_ENABLED=true;c.isCurrentSession=(g,u,s)=>g===1&&u==='u'&&s==='s';c.document={body:{},getElementById:()=>null,addEventListener(){}};c.MutationObserver=class{observe(){}};c.updateOfflineModeBanner=()=>{};c.safetyCall=async()=>{};vm.runInContext(ops,c);return f;}
test('draft request ID survives lost response and queue retry while another draft remains untouched',async()=>{const f=operationsFixture(),a=f.api.saveStock('u','s',null,{itemId:'a'}),b=f.api.saveStock('u','s',null,{itemId:'b'}),sent=[];f.c.safetyCall=async(_,request)=>{sent.push(request.requestId);throw Error('lost response')};await assert.rejects(f.c.operationsSubmit('requestStock',{itemId:'a',quantityMilli:1000,purpose:'Test'},a.id));assert.equal(f.c.operationsQueueRead()[0].request.requestId,a.id);f.api.removeStock('u','s',a.id);assert.equal(f.api.listStock('u','s')[0].id,b.id);f.c.safetyCall=async(_,request)=>sent.push(request.requestId);await f.c.flushPendingSchoolOperationWrites();assert.deepEqual(sent,[a.id,a.id]);assert.equal(f.c.operationsQueueRead().length,0);});
test('separate draft submissions use distinct identifiers and inactive or offline sessions still cannot upload',async()=>{const f=operationsFixture(),ids=[],a=f.api.saveStock('u','s',null,{itemId:'a'}),b=f.api.saveStock('u','s',null,{itemId:'b'});f.c.safetyCall=async(_,request)=>ids.push(request.requestId);await f.c.operationsSubmit('requestStock',{itemId:'a'},a.id);await f.c.operationsSubmit('requestStock',{itemId:'b'},b.id);assert.deepEqual(ids,[a.id,b.id]);f.c.navigator.onLine=false;await assert.rejects(f.c.operationsSubmit('requestStock',{itemId:'a'},a.id));assert.equal(ids.length,2);});
