const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const app=fs.readFileSync('app-4.js','utf8'),sw=fs.readFileSync('sw.js','utf8');
const helper=app.slice(app.indexOf('const NOTIFICATION_TAP_SESSION_KEY = '),app.indexOf('function browserNotificationsEnabled()'));
function page(storage=new Map()){
 let opened=0,hidden=true;const sent=[],blocked=new Set(),frames=[];
 const dialog={classList:{contains:()=>hidden}},c={URL,URLSearchParams,Date,currentUid:null,currentSchoolId:'school',sessionGeneration:1,sessionReady:false,sessionDataReady:false,currentStatus:null,notificationOpenFromLink:false,navigator:{serviceWorker:{controller:{postMessage:m=>sent.push(m)}}},schoolHubServiceWorkerRegistration:null,sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},document:{documentElement:{classList:{contains:k=>blocked.has(k)}},getElementById:()=>dialog},isCurrentSession:(token,uid,school)=>token===c.sessionGeneration&&uid===c.currentUid&&school===c.currentSchoolId,hideSessionRestoring:()=>blocked.delete('sessionRestoring'),requestAnimationFrame:fn=>frames.push(fn),showNotificationCenter:()=>{opened++;hidden=false;},window:{location:{href:'https://app.test/?notifications=1',search:'?notifications=1'},history:{state:null,replaceState(){}}}};
 vm.createContext(c);vm.runInContext(helper,c);
 return {c,sent,blocked,storage,get opened(){return opened;},paint(){while(frames.length)frames.shift()();},hide(){hidden=true;},ready(){Object.assign(c,{currentUid:'teacher',sessionReady:true,sessionDataReady:true,currentStatus:'active'});}};
}
test('tap received during restoration waits for the active school session',()=>{const f=page();f.c.queueNotificationTap({uid:'teacher',tapId:'tap'});assert.equal(f.opened,0);f.ready();f.c.flushNotificationTap();assert.equal(f.opened,1);assert.equal(f.sent.length,0);f.paint();assert.equal(f.sent[0].type,'ACK_NOTIFICATION_TAP');});
test('tap for a different account never opens that account notification window',()=>{const f=page();f.ready();f.c.queueNotificationTap({uid:'other',tapId:'wrong'});assert.equal(f.opened,0);});
test('duplicate delivery of one tap cannot reopen the notification dialog',()=>{const f=page();f.ready();f.c.queueNotificationTap({uid:'teacher',tapId:'same'});f.paint();for(let i=0;i<3;i++)f.c.queueNotificationTap({uid:'teacher',tapId:'same'});assert.equal(f.opened,1);});
test('cold-start link opens only after school data is ready',()=>{const f=page();f.c.notificationOpenFromLink=true;f.c.flushNotificationTap();assert.equal(f.opened,0);f.ready();f.c.flushNotificationTap();assert.equal(f.opened,1);});
function worker(){const handlers={},maps=new Map(),sent=[];const cache=name=>{if(!maps.has(name))maps.set(name,new Map());const m=maps.get(name);return {put:async(k,v)=>m.set(k,v),match:async k=>m.get(k)?.clone(),delete:async k=>m.delete(k)};};const c={URL,Response,console,Date,Map,self:{location:{href:'https://app.test/sw.js'},addEventListener:(n,f)=>(handlers[n]??=[]).push(f),clients:{matchAll:async()=>[],openWindow:async()=>{}},skipWaiting(){}},caches:{open:async n=>cache(n),keys:async()=>[],delete:async()=>{}},fetch:async()=>{}};vm.createContext(c);vm.runInContext(sw,c);const client={url:'https://app.test/',postMessage:m=>sent.push(m)};return {c,maps,sent,async message(data,ports=[]){const work=[];for(const h of handlers.message)h({data,ports,source:client,waitUntil:p=>work.push(p)});await Promise.all(work);}};}
test('worker retains a tap for a page that was not yet listening and clears only the acknowledged tap',async()=>{const f=worker(),tap=await f.c.retainNotificationTap({data:{recipientUid:'teacher'}});await f.message({type:'CHECK_NOTIFICATION_TAP',uid:'teacher'});assert.equal(f.sent[0].tapId,tap.tapId);await f.message({type:'ACK_NOTIFICATION_TAP',tapId:'older',uid:'teacher'});assert(await f.c.readNotificationTap());await f.message({type:'ACK_NOTIFICATION_TAP',tapId:tap.tapId,uid:'teacher'});assert.equal(await f.c.readNotificationTap(),null);});
test('worker does not deliver stored intent to a different account',async()=>{const f=worker();await f.c.retainNotificationTap({data:{recipientUid:'teacher'}});await f.message({type:'CHECK_NOTIFICATION_TAP',uid:'other'});assert.equal(f.sent.length,0);assert(await f.c.readNotificationTap());});
test('expired tap cannot replay after a later app opening',async()=>{const f=worker();await f.c.retainNotificationTap({data:{recipientUid:'teacher'}});f.c.Date={now:()=>Date.now()+6*60*1000};await f.message({type:'CHECK_NOTIFICATION_TAP',uid:'teacher'});assert.equal(f.sent.length,0);});

test('session reset between opening and paint cannot acknowledge or lose the route',()=>{const f=page();f.ready();f.c.queueNotificationTap({uid:'teacher',tapId:'reset'});f.c.sessionGeneration++;f.c.sessionDataReady=false;f.c.preserveNotificationRoute();f.hide();f.paint();assert.equal(f.sent.length,0);f.ready();f.c.flushNotificationTap();f.paint();assert.equal(f.opened,2);assert.equal(f.sent[0].tapId,'reset');});
test('route survives page reload in the same window until the user closes it',()=>{const first=page();first.ready();first.c.queueNotificationTap({uid:'teacher',tapId:'reload'});first.paint();const second=page(first.storage);second.ready();second.c.flushNotificationTap();second.paint();assert.equal(second.opened,1);second.c.clearNotificationRoute();const third=page(second.storage);third.ready();third.c.flushNotificationTap();assert.equal(third.opened,0);});
test('restoring and PIN overlays defer notification display and acknowledgement',()=>{for(const gate of ['sessionRestoring','authing','locked']){const f=page();f.ready();f.blocked.add(gate);f.c.queueNotificationTap({uid:'teacher',tapId:gate});f.paint();assert.equal(f.opened,0);assert.equal(f.sent.length,0);f.blocked.delete(gate);f.c.flushNotificationTap();f.paint();assert.equal(f.opened,1);}});
test('hidden dialog is not acknowledged as displayed',()=>{const f=page();f.ready();f.c.queueNotificationTap({uid:'teacher',tapId:'hidden'});f.hide();f.paint();assert.equal(f.sent.length,0);});
test('worker version reports the actual worker cache name',async()=>{const f=worker();await f.message({type:'GET_WORKER_VERSION'});assert.equal(f.sent[0].type,'SCHOOLHUB_WORKER_VERSION');assert.equal(f.sent[0].cacheName,'schoolhub-cache-v40-private-images-1-notification-tap-7');});

test('cache-version query reads the controlling worker rather than an unrelated active registration',async()=>{const f=page();f.c.MessageChannel=class {constructor(){this.port1={onmessage:null,close(){}};this.port2={close(){},postMessage:data=>this.port1.onmessage({data})};}};f.c.setTimeout=setTimeout;f.c.clearTimeout=clearTimeout;f.c.navigator.serviceWorker.controller.postMessage=(message,ports)=>{assert.equal(message.type,'GET_WORKER_VERSION');ports[0].postMessage({type:'SCHOOLHUB_WORKER_VERSION',cacheName:'actual-controller-cache'});};assert.equal(await f.c.readControllingWorkerCacheVersion({active:{postMessage(){assert.fail('wrong worker');}}}),'actual-controller-cache');});
test('older worker without a version response reports unavailable rather than inventing a cache version',async()=>{const f=page();f.c.MessageChannel=class {constructor(){this.port1={close(){}};this.port2={close(){}};}};f.c.setTimeout=fn=>{queueMicrotask(fn);return 0;};f.c.clearTimeout=()=>{};assert.equal(await f.c.readControllingWorkerCacheVersion({active:null}),'unavailable');});

test('startup mask remains until the local notification destination is known, then reveals directly',async()=>{const f=page();f.ready();f.blocked.add('sessionRestoring');let complete;f.c.readStartupNotificationTap=()=>new Promise(resolve=>complete=resolve);const reveal=f.c.revealSchoolStartup();assert(f.blocked.has('sessionRestoring'));assert.equal(f.opened,0);complete({uid:'teacher',tapId:'direct',at:Date.now()});await reveal;assert(!f.blocked.has('sessionRestoring'));assert.equal(f.opened,1);f.paint();assert.equal(f.sent[0].type,'ACK_NOTIFICATION_TAP');});
test('normal startup reveals the saved page without opening Notifications',async()=>{const f=page();f.ready();f.blocked.add('sessionRestoring');f.c.readStartupNotificationTap=async()=>null;await f.c.revealSchoolStartup();assert(!f.blocked.has('sessionRestoring'));assert.equal(f.opened,0);});
test('an older startup completion cannot reveal a different account or unverified session',async()=>{const f=page();f.ready();f.blocked.add('sessionRestoring');let complete;f.c.readStartupNotificationTap=()=>new Promise(resolve=>complete=resolve);const reveal=f.c.revealSchoolStartup();f.c.sessionGeneration++;f.c.currentUid='other';complete(null);assert.equal(await reveal,false);assert(f.blocked.has('sessionRestoring'));assert.equal(f.opened,0);});
test('reveal never opens school data before verification and hydration are ready',async()=>{const f=page();f.blocked.add('sessionRestoring');assert.equal(await f.c.revealSchoolStartup(),false);f.ready();f.c.sessionDataReady=false;assert.equal(await f.c.revealSchoolStartup(),false);assert(f.blocked.has('sessionRestoring'));});
test('an older worker with no startup route response has a bounded local wait',async()=>{const f=page();f.c.MessageChannel=class {constructor(){this.port1={close(){}};this.port2={close(){}};}};let delay;f.c.setTimeout=(fn,ms)=>{delay=ms;queueMicrotask(fn);return 0;};f.c.clearTimeout=()=>{};assert.equal(await f.c.readStartupNotificationTap('teacher'),null);assert.equal(delay,400);});

test('startup route handshake replies with no route, scoped route, or matching tap through its message port',async()=>{const f=worker(),replies=[],port={postMessage:data=>replies.push(data)};await f.message({type:'CHECK_NOTIFICATION_TAP',uid:'teacher'},[port]);assert.equal(replies.pop().tap,null);const tap=await f.c.retainNotificationTap({data:{recipientUid:'teacher'}});await f.message({type:'CHECK_NOTIFICATION_TAP',uid:'other'},[port]);assert.equal(replies.pop().tap,null);await f.message({type:'CHECK_NOTIFICATION_TAP',uid:'teacher'},[port]);assert.equal(replies.pop().tap.tapId,tap.tapId);assert.equal(f.sent.length,0);});
