const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const app=fs.readFileSync('app-4.js','utf8'),sw=fs.readFileSync('sw.js','utf8');
const helper=app.slice(app.indexOf('const notificationTapQuery = '),app.indexOf('function browserNotificationsEnabled()'));
function page(){let opened=0;const sent=[],c={URL,URLSearchParams,currentUid:null,sessionReady:false,sessionDataReady:false,currentStatus:null,notificationOpenFromLink:false,navigator:{serviceWorker:{controller:{postMessage:m=>sent.push(m)}}},schoolHubServiceWorkerRegistration:null,showNotificationCenter:()=>opened++,window:{location:{href:'https://app.test/?notifications=1',search:'?notifications=1'},history:{state:null,replaceState(){}}}};vm.createContext(c);vm.runInContext(helper,c);return {c,sent,get opened(){return opened;},ready(){Object.assign(c,{currentUid:'teacher',sessionReady:true,sessionDataReady:true,currentStatus:'active'});}};}
test('tap received during restoration waits for the active school session',()=>{const f=page();f.c.queueNotificationTap({uid:'teacher',tapId:'tap'});assert.equal(f.opened,0);f.ready();f.c.flushNotificationTap();assert.equal(f.opened,1);assert.equal(f.sent[0].type,'ACK_NOTIFICATION_TAP');});
test('tap for a different account never opens that account notification window',()=>{const f=page();f.ready();f.c.queueNotificationTap({uid:'other',tapId:'wrong'});assert.equal(f.opened,0);});
test('duplicate delivery of one tap cannot reopen the notification dialog',()=>{const f=page();f.ready();for(let i=0;i<3;i++)f.c.queueNotificationTap({uid:'teacher',tapId:'same'});assert.equal(f.opened,1);});
test('cold-start link opens only after school data is ready',()=>{const f=page();f.c.notificationOpenFromLink=true;f.c.flushNotificationTap();assert.equal(f.opened,0);f.ready();f.c.flushNotificationTap();assert.equal(f.opened,1);});
function worker(){const handlers={},maps=new Map(),sent=[];const cache=name=>{if(!maps.has(name))maps.set(name,new Map());const m=maps.get(name);return {put:async(k,v)=>m.set(k,v),match:async k=>m.get(k)?.clone(),delete:async k=>m.delete(k)};};const c={URL,Response,console,Date,Map,self:{location:{href:'https://app.test/sw.js'},addEventListener:(n,f)=>(handlers[n]??=[]).push(f),clients:{matchAll:async()=>[],openWindow:async()=>{}},skipWaiting(){}},caches:{open:async n=>cache(n),keys:async()=>[],delete:async()=>{}},fetch:async()=>{}};vm.createContext(c);vm.runInContext(sw,c);const client={url:'https://app.test/',postMessage:m=>sent.push(m)};return {c,maps,sent,async message(data){const work=[];for(const h of handlers.message)h({data,source:client,waitUntil:p=>work.push(p)});await Promise.all(work);}};}
test('worker retains a tap for a page that was not yet listening and clears only the acknowledged tap',async()=>{const f=worker(),tap=await f.c.retainNotificationTap({data:{recipientUid:'teacher'}});await f.message({type:'CHECK_NOTIFICATION_TAP',uid:'teacher'});assert.equal(f.sent[0].tapId,tap.tapId);await f.message({type:'ACK_NOTIFICATION_TAP',tapId:'older',uid:'teacher'});assert(await f.c.readNotificationTap());await f.message({type:'ACK_NOTIFICATION_TAP',tapId:tap.tapId,uid:'teacher'});assert.equal(await f.c.readNotificationTap(),null);});
test('worker does not deliver stored intent to a different account',async()=>{const f=worker();await f.c.retainNotificationTap({data:{recipientUid:'teacher'}});await f.message({type:'CHECK_NOTIFICATION_TAP',uid:'other'});assert.equal(f.sent.length,0);assert.equal(await f.c.readNotificationTap(),null);});
test('expired tap cannot replay after a later app opening',async()=>{const f=worker();await f.c.retainNotificationTap({data:{recipientUid:'teacher'}});f.c.Date={now:()=>Date.now()+6*60*1000};await f.message({type:'CHECK_NOTIFICATION_TAP',uid:'teacher'});assert.equal(f.sent.length,0);});
