const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync('offline-drafts.js','utf8'),app=fs.readFileSync('app-4.js','utf8'),ops=fs.readFileSync('school-operations.js','utf8'),auth=fs.readFileSync('account-security.js','utf8');
function fixture(storage=new Map()){const c={Date,window:{},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}};vm.createContext(c);vm.runInContext(code,c);return {api:c.window.SchoolHubDrafts,storage,c};}
test('My Details draft survives reopening with original bases and linked Staff ID',()=>{const f=fixture();f.api.write('my-details','teacher','s',{staffRecordId:'staff-1',values:{name:'Draft name',academicQualification:'Diploma'},base:{name:'Original'}});const reopened=fixture(f.storage).api.read('my-details','teacher','s');assert.equal(reopened.values.name,'Draft name');assert.equal(reopened.base.name,'Original');assert.equal(reopened.staffRecordId,'staff-1');});
test('drafts cannot cross account, school or form boundaries',()=>{const f=fixture();f.api.write('stock-request','u','s',{values:{itemId:'item',quantityMilli:'1.250',purpose:'Classroom'}});for(const [kind,uid,school]of [['stock-request','other','s'],['stock-request','u','other'],['my-details','u','s']])assert.equal(f.api.read(kind,uid,school),null);assert.equal(f.api.read('stock-request','u','s').values.quantityMilli,'1.250');});
test('passwords, credential changes and extra request parameters never persist as drafts',()=>{const f=fixture();f.api.write('my-details','u','s',{values:{name:'Test',password:'SECRET',currentPassword:'SECRET'},base:{newPassword:'SECRET'}});f.api.write('stock-request','u','s',{values:{itemId:'item',purpose:'Test',amount:'500',role:'headteacher',password:'SECRET'}});assert(![...f.storage.values()].join('').includes('SECRET'));assert(!f.api.read('stock-request','u','s').values.amount);assert.throws(()=>f.api.write('login','u','s',{values:{}}));});
test('discard only removes the selected form draft',()=>{const f=fixture();for(const kind of ['my-details','stock-request'])f.api.write(kind,'u','s',{values:{}});f.api.remove('my-details','u','s');assert.equal(f.api.read('my-details','u','s'),null);assert(f.api.read('stock-request','u','s'));});
test('storage and corrupt draft failures are exposed without overwriting saved content',()=>{const f=fixture();f.api.write('my-details','u','s',{values:{name:'Original'}});f.c.localStorage.setItem=()=>{throw Error('Full')};assert.throws(()=>f.api.write('my-details','u','s',{values:{name:'Changed'}}),/Full/);assert.equal(f.api.read('my-details','u','s').values.name,'Original');const key=[...f.storage.keys()][0];f.storage.set(key,'broken');assert.throws(()=>f.api.read('my-details','u','s'));assert.equal(f.storage.get(key),'broken');});
test('profile and stock drafts are explicit submissions with preserved conflict bases',()=>{assert(app.includes('base[key]=original[key]'));assert(app.includes("if(navigator.onLine===false||offlineAuthenticatedMode){status.textContent='Draft saved"));assert(ops.includes("if(navigator.onLine===false||offlineAuthenticatedMode){status.textContent='Draft saved"));assert(ops.includes("await operationsSubmit(action,values)"));assert(app.includes("draft.staffRecordId!==loaded.staffRecordId"));});
test('offline/unverified login UI gates before working state and credentials stay unqueued',()=>{const guard=auth.indexOf("if(navigator.onLine===false||offlineAuthenticatedMode){status.textContent='Connect");assert(guard>0);assert(guard<auth.indexOf("busy=true;dialog.dataset.busy"));assert(!auth.includes('SchoolHubDrafts'));assert(auth.includes('clearTimeout(slow)'));assert(auth.includes("input[type=\"password\"]"));});
test('new draft assets are mirrored and loaded before app handlers',()=>{assert.equal(code,fs.readFileSync('public/offline-drafts.js','utf8'));const html=fs.readFileSync('index.html','utf8');assert(html.indexOf('src="offline-drafts.js')<html.indexOf('src="app-4.js'));assert(fs.readFileSync('sw.js','utf8').includes("'./offline-drafts.js'"));});
