const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');const source=fs.readFileSync('school-operations.js','utf8');
function fixture(){const storage=new Map(),status={textContent:'Confirmed records'},host={textContent:'Existing table',querySelector:()=>status,replaceChildren(){this.textContent='';this.clears=(this.clears||0)+1;}},dialog={remove(){dialog.removed=true}},view={classList:{contains:()=>false}};let observer,calls=0;const data={role:'teacher',items:[],requests:[],assets:[],liabilities:[],history:[]};
const c={console,currentUid:'u',currentSchoolId:'s',currentStatus:'active',sessionGeneration:1,sessionReady:true,sessionDataReady:true,offlineAuthenticatedMode:false,FIREBASE_ENABLED:true,navigator:{onLine:true},isHeadTeacher:()=>false,isCurrentSession:(g,u,s)=>g===c.sessionGeneration&&u===c.currentUid&&s===c.currentSchoolId,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},document:{body:{},visibilityState:'visible',getElementById:id=>id==='operationsWrap'?host:id==='view-operations'?view:id==='operationsDialog'&&c.formOpen?dialog:null,addEventListener(){}},window:{addEventListener(){}},MutationObserver:class{constructor(fn){observer=fn}observe(){}},setInterval(){},updateOfflineModeBanner(){},safetyCall:async()=>{calls++;return data;}};vm.createContext(c);vm.runInContext(source,c);vm.runInContext('operationsState=fixtureData;operationsStateContext=operationsSession();',Object.assign(c,{fixtureData:data}));const renders=[];c.operationsRender=(d,s)=>{renders.push(d);host.textContent='Updated table'};return {c,host,status,dialog,data,renders,storage,observe:()=>observer(),calls:()=>calls};}
test('routine school-data hydration preserves operation records and open forms while writes remain blocked',()=>{const f=fixture();f.c.formOpen=true;f.c.sessionDataReady=false;f.observe();assert(!f.dialog.removed);assert.equal(f.host.textContent,'Existing table');assert.equal(f.c.operationsActive(f.c.operationsSession()),false);});
test('account, school, generation, role or disabled membership changes clear old records and dialogs',()=>{for(const change of [{currentUid:'other'},{currentSchoolId:'other'},{sessionGeneration:2},{currentStatus:'disabled'},{sessionReady:false},{isHeadTeacher:()=>true}]){const f=fixture();f.c.formOpen=true;Object.assign(f.c,change);f.observe();assert(f.dialog.removed);assert.equal(f.host.textContent,'');}});
test('confirmed stock save cache invalidation cannot blank the current table during scoped fetch',async()=>{const f=fixture();let finish;f.c.safetyCall=()=>new Promise(resolve=>finish=resolve);const p=f.c.renderSchoolOperations();while(!finish)await new Promise(r=>setImmediate(r));assert.equal(f.host.textContent,'Existing table');assert.equal(f.renders.length,0);finish({...f.data,revision:1});await p;assert.equal(f.renders.length,1);assert.equal(f.host.textContent,'Updated table');});
test('failed scoped refresh leaves saved records visible and reports cached state',async()=>{const f=fixture();f.c.safetyCall=async()=>{throw Error('Network delayed')};await f.c.renderSchoolOperations(true);assert.equal(f.host.textContent,'Existing table');assert.match(f.status.textContent,/Cached records shown.*Network delayed/);});
test('section refresh skips hidden, offline, unverified and open-form cases without starting whole-school recovery',async()=>{for(const change of [{offlineAuthenticatedMode:true},{sessionDataReady:false},{formOpen:true},{navigator:{onLine:false}},{documentVisibility:'hidden'}]){const f=fixture();if(change.documentVisibility)f.c.document.visibilityState='hidden';else Object.assign(f.c,change);f.c.revalidateAndSyncAfterReconnect=()=>{throw Error('Unexpected recovery')};assert.equal(await f.c.operationsRefreshVisible(),false);assert.equal(f.calls(),0);}});
test('visible refresh shares one fetch and updates only the operations section',async()=>{const f=fixture();let finish;f.c.safetyCall=()=>new Promise(resolve=>finish=resolve);f.c.revalidateAndSyncAfterReconnect=()=>{throw Error('Unexpected recovery')};const a=f.c.operationsRefreshVisible(),b=f.c.operationsRefreshVisible();assert.equal(a,b);while(!finish)await new Promise(r=>setImmediate(r));assert.equal(f.host.textContent,'Existing table');finish({...f.data,revision:1});await a;assert.equal(f.renders.length,1);});
test('session switch during scoped refresh cannot display an old school response',async()=>{const f=fixture();let finish;f.c.safetyCall=()=>new Promise(resolve=>finish=resolve);const p=f.c.renderSchoolOperations();while(!finish)await new Promise(r=>setImmediate(r));f.c.currentSchoolId='other';f.observe();finish({...f.data,revision:1});await p;assert.equal(f.renders.length,0);assert.equal(f.host.textContent,'');});

test('unchanged server records do not repaint the table during a quiet refresh',async()=>{const f=fixture();await f.c.renderSchoolOperations(true);assert.equal(f.host.textContent,'Existing table');assert.equal(f.renders.length,0);assert.match(f.status.textContent,/Confirmed school records/);});
