const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const app=fs.readFileSync('app-4.js','utf8'),start=app.indexOf('function validateCoreBackupForImport('),end=app.indexOf("document.getElementById('exportBackupBtn')",start),c={};vm.createContext(c);vm.runInContext(app.slice(start,end),c);const valid={app:'AlatiphA SchoolHub',type:'core-school-records',schoolId:'A',data:{classes:[{id:'c'}],students:[{id:'p',classId:'c'}],staff:[],settings:{schoolName:'Synthetic'}}},head={cloud:true,head:true,ready:true,online:true,schoolId:'A'};
test('backup from another school or an unscoped legacy file is rejected before any import',()=>{for(const schoolId of ['B',null,undefined])assert.throws(()=>c.validateCoreBackupForImport({...valid,schoolId},head));assert.doesNotThrow(()=>c.validateCoreBackupForImport({...valid,schoolId:null},{cloud:false}));});
test('teacher, unloaded and offline cloud imports are rejected',()=>{for(const change of [{head:false},{ready:false},{online:false}])assert.throws(()=>c.validateCoreBackupForImport(valid,{...head,...change}));});
test('malformed and duplicate core records cannot be imported',()=>{for(const data of [{students:'bad'},{students:[{id:'same'},{id:'same'}]},{settings:[]},{staff:[{id:'bad/path'}]},{}])assert.throws(()=>c.validateCoreBackupForImport({...valid,data},head));});
test('same-school core backup round trip retains all exported core fields',()=>{const original={...valid,data:{...valid.data,subjects:[{id:'math'}],grades:{c:{p:{math:{e:80}}}},attendance:{day:{p:'P'}},teacherAttendance:{},schoolCalendar:{},remarks:{p:'Good'}}};const result=c.validateCoreBackupForImport(JSON.parse(JSON.stringify(original)),head);assert.deepEqual(JSON.parse(JSON.stringify(result)),original.data);});
test('year-end snapshots require their dedicated recovery workflow',()=>assert.throws(()=>c.validateCoreBackupForImport({...valid,type:'academic-year-rollover'},head)));
function importFixture(){let handler,reader;const writes=[],alerts=[];const ctx={currentUid:'head',currentSchoolId:'A',sessionGeneration:1,FIREBASE_ENABLED:true,sessionDataReady:true,cloudHydrationInProgress:false,offlineAuthenticatedMode:false,navigator:{onLine:true},isActiveGuest:()=>false,isHeadTeacher:()=>true,requireHeadTeacher:()=>true,alert:s=>alerts.push(s),confirm:()=>true,backupLocalSchoolData:()=>true,auditAction:()=>{},location:{reload(){}},KEYS:Object.fromEntries(['settings','classes','subjects','students','grades','attendance','teacherAttendance','schoolCalendar','remarks','staff'].map(k=>[k,k])),DB:{set:(k,v)=>writes.push([k,v])},FileReader:class{constructor(){reader=this;}readAsText(){}},document:{getElementById:()=>({addEventListener:(_,fn)=>handler=fn})}};vm.createContext(ctx);vm.runInContext(app.slice(start,end),ctx);const begin=app.indexOf("document.getElementById('importBackupInput').addEventListener"),finish=app.indexOf('/* ---------- Classes ---------- */',begin);vm.runInContext(app.slice(begin,finish),ctx);const event={target:{files:[{size:100}],value:'chosen'}};handler(event);return {ctx,writes,alerts,event,finish(value=valid){reader.result=JSON.stringify(value);reader.onload();}};}
test('an account or school switch while FileReader is pending produces no local writes',()=>{for(const changes of [{currentUid:'different'},{currentSchoolId:'B'},{sessionGeneration:2}]){const f=importFixture();Object.assign(f.ctx,changes);f.finish();assert.equal(f.writes.length,0);assert(f.alerts.some(x=>x.includes('changed')));}});
test('failed pre-import recovery snapshot stops all backup writes',()=>{const f=importFixture();f.ctx.backupLocalSchoolData=()=>false;f.finish();assert.equal(f.writes.length,0);assert(f.alerts.some(x=>x.includes('snapshot')));});
test('same-school import writes only the backed-up core records after recovery checkpoint',()=>{const f=importFixture();let checkpoint=false;f.ctx.backupLocalSchoolData=()=>{checkpoint=true;return true;};f.ctx.DB.set=(k,v)=>{assert(checkpoint);f.writes.push([k,v]);};f.finish();assert.deepEqual(f.writes.map(x=>x[0]).sort(),Object.keys(valid.data).sort());});
