const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function fixture(){
 const elements=new Map(),make=id=>({id,textContent:'',disabled:false,onclick:null,focus(){},classList:{set:new Set(['hidden']),add(x){this.set.add(x)},remove(x){this.set.delete(x)},contains(x){return this.set.has(x)}}});for(const id of ['emailVerificationGate','verificationEmail','verificationStatus','verificationResendBtn','verificationCheckBtn','verificationLogoutBtn'])elements.set(id,make(id));
 let sent=0,refreshed=0,reloaded=0,signedOut=0,sendError=false;
 const user={uid:'u',email:'new@example.test',emailVerified:false,sendEmailVerification:async()=>{sent++;if(sendError)throw Error('network failed');},reload:async()=>{},getIdToken:async force=>{assert.equal(force,true);refreshed++;}},auth={currentUser:user},storage=new Map();
 const context={document:{getElementById:id=>elements.get(id),documentElement:make('html')},window:{location:{reload:()=>reloaded++}},firebase:{auth:()=>auth},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setInterval:()=>1,clearInterval:()=>{},setTimeout,clearTimeout,Date,resetWorkspaceState(){},signOutAndReset:()=>signedOut++};vm.createContext(context);vm.runInContext(fs.readFileSync('email-verification.js','utf8'),context);return {api:context.window.SchoolHubEmailVerification,e:elements,user,auth,storage,counts:()=>({sent,refreshed,reloaded,signedOut}),failSend:()=>sendError=true};
}
test('verification routing preserves active legacy access but gates new and pending accounts',()=>{const f=fixture();assert.equal(f.api.required(f.user,null),true);assert.equal(f.api.required(f.user,{schoolId:'s',status:'pending'}),true);assert.equal(f.api.required(f.user,{schoolId:'s',status:'active'}),false);assert.equal(f.api.required(f.user,{schoolId:'s',status:'disabled'}),false);f.user.emailVerified=true;assert.equal(f.api.required(f.user,null),false);});
test('signup sends once, shows the email and applies resend cooldown',async()=>{const f=fixture();f.api.show(f.user);await Promise.all([f.api.send(f.user),f.api.send(f.user)]);assert.equal(f.counts().sent,1);assert.equal(f.e.get('verificationEmail').textContent,'new@example.test');assert(f.e.get('verificationStatus').textContent.includes('Verification email sent'));assert.equal(f.e.get('verificationResendBtn').disabled,true);f.api.hide();});
test('failed delivery keeps account verification visible and offers retry',async()=>{const f=fixture();f.failSend();f.api.show(f.user);assert.equal(await f.api.send(f.user),false);assert(f.e.get('verificationStatus').textContent.includes('could not be sent'));assert.equal(f.e.get('verificationResendBtn').disabled,false);f.api.hide();});
test('rechecking an unverified email cannot enter the app; verification refreshes claims before reopening',async()=>{const f=fixture();f.api.show(f.user);await f.e.get('verificationCheckBtn').onclick();assert.equal(f.counts().reloaded,0);assert.equal(f.counts().refreshed,0);f.user.emailVerified=true;await f.e.get('verificationCheckBtn').onclick();assert.equal(f.counts().refreshed,1);assert.equal(f.counts().reloaded,1);f.api.hide();});
test('an account switch while verification is being checked cannot reopen the previous account',async()=>{const f=fixture();f.api.show(f.user);f.user.reload=async()=>{f.user.emailVerified=true;f.auth.currentUser={uid:'other'};};await f.e.get('verificationCheckBtn').onclick();assert.equal(f.counts().reloaded,0);assert.equal(f.counts().refreshed,0);f.api.hide();});
test('profile contains account buttons and relocated tools keep one existing handler target',()=>{const html=fs.readFileSync('index.html','utf8'),menu=html.slice(html.indexOf('<div id="profileDropdown"'),html.indexOf('</header>'));for(const id of ['profileMyDetailsBtn','profileAccountSecurityBtn','logoutBtn','profileLoginBtn'])assert(menu.includes('id="'+id+'"'));for(const id of ['profileSetupLink','profileSyncCenterBtn','profileSystemHealthBtn','profileTourBtn','profileBillingBtn','profileNotificationsBtn','profileInstallBtn','profileAboutBtn']){assert(!menu.includes('id="'+id+'"'));assert.equal(html.split('id="'+id+'"').length-1,1);}assert(html.includes('id="notificationBtn"'));assert(html.includes('id="syncStatusBtn"'));});
