const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const script=fs.readFileSync('staff-add-draft.js','utf8');
function fixture(storage=new Map(),images=new Map()){
 const nodes=new Map(),listeners={};function node(){return {value:'',disabled:false,files:[],hidden:false,style:{},classList:{add(){},remove(){}},listeners:{},addEventListener(k,fn){(this.listeners[k]??=[]).push(fn)},dispatch(k){for(const fn of this.listeners[k]||[])fn()},append(n){if(n.id)nodes.set(n.id,n)},after(){},setAttribute(){},removeAttribute(){},querySelectorAll:()=>[...nodes.values()].filter(n=>n.control),focus(){}};}
 for(const id of ['addStaffForm','toggleAddStaffBtn','addStaffBtn','newStaffName','newStaffRole','newStaff_staffId','newStaff_bankAccount','newStaff_academicQualification','newStaffSignature']){const n=node();n.control=id.startsWith('newStaff')||id==='addStaffBtn';nodes.set(id,n);}const c={globalGuest:false,window:{addEventListener:(k,fn)=>listeners[k]=fn},document:{hidden:false,getElementById:id=>nodes.get(id),createElement:node,addEventListener:(k,fn)=>listeners[k]=fn},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},crypto:{randomUUID:()=>Math.random().toString(36)},File,Uint8Array,atob,Date,Promise,fileToDataUrl:async()=> 'data:image/png;base64,YWJj',isDataImage:s=>s.startsWith('data:image/'),getCachedLocalImageAsync:async k=>images.get(k)?.dataUrl||'',removeCachedLocalImage:k=>images.delete(k),openImageDB:async()=>({transaction:()=>{const tx={objectStore:()=>({put:(v,k)=>{images.set(k,v);queueMicrotask(()=>tx.oncomplete())}})};return tx;}})};
 vm.createContext(c);vm.runInContext("let currentUid='head1',currentSchoolId='school1',currentStatus='active',currentRole='headteacher';const STAFF_FIELDS=[{key:'staffId'},{key:'bankAccount'},{key:'academicQualification'}],IMAGE_DB_STORE='images';const isHeadTeacher=()=>currentRole==='headteacher',isActiveGuest=()=>globalGuest;function renderStaff(){}function resetWorkspaceState(){currentUid=null;currentSchoolId=null;}"+script,c);return {c,nodes,storage,images,run:s=>vm.runInContext(s,c),api:c.window.SchoolHubStaffAddDraft,key:'schoolhub_add_staff_draft_v1_'+JSON.stringify(['head1','school1'])};
}
test('entered staff fields and qualification survive a reload in the same account',()=>{const f=fixture();f.nodes.get('newStaffName').value='TEST STAFF';f.nodes.get('newStaff_bankAccount').value='SYNTHETIC';f.nodes.get('newStaff_academicQualification').value='Diploma';f.nodes.get('addStaffForm').dispatch('input');const reopened=fixture(f.storage,f.images);for(const id of ['newStaffName','newStaff_bankAccount','newStaff_academicQualification'])assert.equal(reopened.nodes.get(id).value,f.nodes.get(id).value);});
test('signature bytes survive reload and reconstruct a selected file',async()=>{const f=fixture();f.nodes.get('newStaffName').value='TEST STAFF';f.nodes.get('newStaffSignature').files=[new File(['abc'],'test.png',{type:'image/png'})];f.nodes.get('newStaffSignature').dispatch('change');await f.api.file();const reopened=fixture(f.storage,f.images),file=await reopened.api.file();assert.equal(file.name,'test.png');assert.equal(await file.text(),'abc');assert.equal(file.type,'image/png');});
test('account reset hides old fields; another account cannot restore them',()=>{const f=fixture();f.nodes.get('newStaffName').value='PRIVATE DRAFT';f.api.stash();f.c.resetWorkspaceState();assert.equal(f.nodes.get('newStaffName').value,'');f.run("currentUid='head2';currentSchoolId='school1'");f.api.ensure();assert.equal(f.nodes.get('newStaffName').value,'');f.run("currentUid='head1'");f.api.ensure();assert.equal(f.nodes.get('newStaffName').value,'PRIVATE DRAFT');});
test('storage failure leaves typed values intact and displays a recoverable error',()=>{const f=fixture();f.c.localStorage.setItem=()=>{throw Error('Quota');};f.nodes.get('newStaffName').value='KEEP ME';f.api.stash();assert.equal(f.nodes.get('newStaffName').value,'KEEP ME');assert.match(f.nodes.get('addStaffDraftStatus').textContent,/could not be saved/);});
test('failed signature draft persistence does not discard staff fields',async()=>{const f=fixture();f.nodes.get('newStaffName').value='KEEP DETAILS';f.c.openImageDB=async()=>null;f.nodes.get('newStaffSignature').files=[new File(['abc'],'test.png',{type:'image/png'})];f.nodes.get('newStaffSignature').dispatch('change');const file=await f.api.file();assert.equal(file.name,'test.png');assert.equal(JSON.parse(f.storage.get(f.key)).values.name,'KEEP DETAILS');assert.match(f.nodes.get('addStaffDraftStatus').textContent,/could not be saved/);});
test('clearing a successful or discarded draft removes its text and signature reservation',async()=>{const f=fixture();f.nodes.get('newStaffName').value='TEST STAFF';f.nodes.get('newStaffSignature').files=[new File(['abc'],'test.png',{type:'image/png'})];f.nodes.get('newStaffSignature').dispatch('change');await f.api.file();f.api.clear();assert.equal(f.storage.size,0);assert.equal(f.images.size,0);});
const app=fs.readFileSync('app-4.js','utf8'),start=app.indexOf("document.getElementById('addStaffBtn').addEventListener('click', async () => {"),end=app.indexOf('\n\n\n\n/* ---------- Inline Help',start),handler=app.slice(start,end);
function saveFixture(){let resolveFile;const fileWait=new Promise(r=>resolveFile=r),records=[],nodes=new Map(),controls=[];for(const id of ['addStaffBtn','newStaffName','newStaff_staffId','newStaffRole','newStaffSignature','addStaffValidation','toggleAddStaffBtn']){const n={value:id==='newStaffName'?'TEST STAFF':id==='newStaff_staffId'?'TEST-123':id==='newStaffRole'?'Teacher':'',disabled:false,files:[],classList:{add(){},remove(){}},setAttribute(){},focus(){}};nodes.set(id,n);controls.push(n);}let callback,cleared=0;nodes.get('addStaffBtn').addEventListener=(_,fn)=>callback=fn;const c={document:{getElementById:id=>nodes.get(id)},STAFF_FIELDS:[{key:'staffId'}],KEYS:{staff:'staff'},DB:{get:()=>records.slice(),set:(_,v)=>{records.splice(0,records.length,...v)}},SchoolHubStaffAddDraft:{stash(){},file:()=>fileWait,clear:()=>cleared++},requireHeadTeacher:()=>true,isActiveGuest:()=>false,isCurrentSession:(token,user,school)=>token===c.sessionGeneration&&user===c.currentUid&&school===c.currentSchoolId,sessionGeneration:1,currentUid:'head1',currentSchoolId:'school1',currentStatus:'active',sessionReady:true,sessionDataReady:true,cloudHydrationInProgress:false,FIREBASE_ENABLED:true,uid:()=> 'synthetic-staff-id',auditAction(){},renderStaff(){},alert(){},addStaffForm:{querySelectorAll:()=>controls,classList:{add(){}}},toggleAddStaffBtn:nodes.get('toggleAddStaffBtn')};vm.createContext(c);vm.runInContext(handler,c);return {c,nodes,records,resolveFile,save:()=>callback(),cleared:()=>cleared};}
test('duplicate Add Staff clicks during file preparation create only one record',async()=>{const f=saveFixture(),saving=f.save();await f.save();assert.equal(f.records.length,0);f.resolveFile(null);await saving;assert.equal(f.records.length,1);assert.equal(f.cleared(),1);assert.equal(f.nodes.get('newStaffName').value,'');});
test('failed local staff save retains the form and saved draft',async()=>{const f=saveFixture();f.c.DB.set=()=>{throw Error('Disk full');};const saving=f.save();f.resolveFile(null);await saving;assert.equal(f.cleared(),0);assert.equal(f.nodes.get('newStaffName').value,'TEST STAFF');assert.equal(f.nodes.get('addStaffBtn').disabled,false);});
test('account switch during file preparation cannot add staff to another workspace',async()=>{const f=saveFixture(),saving=f.save();f.c.currentUid='head2';f.c.currentSchoolId='school2';f.resolveFile(null);await saving;assert.equal(f.records.length,0);assert.equal(f.cleared(),0);});
test('Staff ID added during file preparation is detected before saving',async()=>{const f=saveFixture(),saving=f.save();f.records.push({id:'other',staffId:'TEST-123'});f.resolveFile(null);await saving;assert.equal(f.records.length,1);assert.equal(f.cleared(),0);assert.equal(f.nodes.get('newStaffName').value,'TEST STAFF');});

test('empty file selection keeps the already saved signature and text draft',async()=>{const f=fixture();f.nodes.get('newStaffName').value='KEEP ME';f.nodes.get('newStaffSignature').files=[new File(['abc'],'test.png',{type:'image/png'})];f.nodes.get('newStaffSignature').dispatch('change');await f.api.file();f.nodes.get('newStaffSignature').files=[];f.nodes.get('newStaffSignature').dispatch('change');assert.equal((await f.api.file()).name,'test.png');assert.equal(f.nodes.get('newStaffName').value,'KEEP ME');});
test('local guest staff drafts use a separate scope and remain usable',async()=>{const f=fixture();f.c.globalGuest=true;f.run("currentUid=null;currentSchoolId=null;currentStatus=null;currentRole=null");f.api.ensure();f.nodes.get('newStaffName').value='GUEST DRAFT';f.api.stash();assert.equal(await f.api.file(),null);assert(f.storage.has('schoolhub_add_staff_draft_v1_'+JSON.stringify(['local-guest','local-guest-workspace'])));});
