const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const app=fs.readFileSync('app-4.js','utf8');
const code=app.slice(app.indexOf('function inspectVerifiedLocalSession('),app.indexOf('function clearVerifiedLocalSession('));
function fixture(){const storage=new Map(),now=2000000000000;class Clock extends Date {static now(){return now;}}const c={Date:Clock,navigator:{onLine:false},verifiedSessionKey:uid=>'cache-'+uid,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)}};vm.createContext(c);vm.runInContext(code,c);const user={uid:'synthetic-user'},good={uid:user.uid,schoolId:'synthetic-school',role:'teacher',status:'active',verifiedAt:now-9*3600000};const put=value=>storage.set('cache-'+user.uid,JSON.stringify(value));return {c,storage,user,good,put,now};}
test('nine-hour cache is eligible; 24-hour expiry is unchanged and rejects older checks',()=>{const f=fixture();f.put(f.good);assert.equal(f.c.loadVerifiedLocalSession(f.user).schoolId,'synthetic-school');f.put({...f.good,verifiedAt:f.now-86400000});assert(f.c.loadVerifiedLocalSession(f.user));f.put({...f.good,verifiedAt:f.now-86400001});assert.equal(f.c.inspectVerifiedLocalSession(f.user).reason,'expired');assert.equal(f.c.loadVerifiedLocalSession(f.user),null);});
test('captures distinct missing, invalid, clock and identity failures without granting access',()=>{const f=fixture();assert.equal(f.c.inspectVerifiedLocalSession(f.user).reason,'missing');f.storage.set('cache-'+f.user.uid,'broken');assert.equal(f.c.inspectVerifiedLocalSession(f.user).reason,'invalid-data');for(const [change,reason] of [[{verifiedAt:null},'invalid-time'],[{verifiedAt:f.now+1},'clock-mismatch'],[{uid:'other-user'},'identity-mismatch'],[{status:'disabled'},'inactive'],[{schoolId:null},'missing-school'],[{role:'owner'},'invalid-role']]){f.put({...f.good,...change});assert.equal(f.c.inspectVerifiedLocalSession(f.user).reason,reason);assert.equal(f.c.loadVerifiedLocalSession(f.user),null);}});
test('capture survives a fresh runtime and a healthy cache refresh without recording private fields',()=>{const f=fixture();f.put({...f.good,verifiedAt:f.now-90000000});const text=f.c.captureStartupFailure(f.user);assert.match(text,/older than 24 hours/);const raw=f.storage.get('arc_startup_failure_diagnostic_v1');assert(!raw.includes('synthetic-user'));assert(!raw.includes('synthetic-school'));f.put(f.good);const fresh=fixture();fresh.storage.set('arc_startup_failure_diagnostic_v1',raw);assert.equal(fresh.c.readStartupFailureDiagnostic(),text);assert.equal(f.c.readStartupFailureDiagnostic(),text);assert(f.c.loadVerifiedLocalSession(f.user));});
test('unreadable storage still reports the reason in memory and does not open a cache',()=>{const f=fixture();f.c.localStorage.getItem=()=>{throw Error('blocked');};f.c.localStorage.setItem=()=>{throw Error('blocked');};assert.equal(f.c.loadVerifiedLocalSession(f.user),null);assert.match(f.c.captureStartupFailure(f.user),/Browser storage could not be read/);assert.match(f.c.readStartupFailureDiagnostic(),/Browser storage could not be read/);});
test('damaged persisted diagnostic cannot inject arbitrary error text',()=>{const f=fixture();f.storage.set('arc_startup_failure_diagnostic_v1',JSON.stringify({version:1,reason:'<unsafe>',at:f.now}));assert.equal(f.c.readStartupFailureDiagnostic(),'');});
