const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const app=fs.readFileSync('app-4.js','utf8'),sw=fs.readFileSync('sw.js','utf8');
const startup=app.slice(app.indexOf('async function schoolAccountForStartup('),app.indexOf('function pendingSyncCountForCurrentSchool('));
function account(online,cached){let reads=0;const c={navigator:{onLine:online},loadVerifiedLocalSession:()=>cached,withSessionVerificationDeadline:async p=>p,firebase:{firestore:()=>({collection:()=>({doc:()=>({get:()=>{reads++;return Promise.resolve('server snapshot');}})})})}};vm.createContext(c);vm.runInContext(startup,c);return {c,reads:()=>reads};}
test('offline startup opens only the existing verified identity cache without issuing a server read',async()=>{const cached={uid:'teacher',schoolId:'school',role:'teacher'},f=account(false,cached);assert.equal((await f.c.schoolAccountForStartup({uid:'teacher'})).cached,cached);assert.equal(f.reads(),0);});
test('online startup retains server account verification; missing offline cache never invents access',async()=>{for(const [online,cached] of [[true,{uid:'teacher'}],[false,null]]){const f=account(online,cached);assert.equal((await f.c.schoolAccountForStartup({uid:'teacher'})).snapshot,'server snapshot');assert.equal(f.reads(),1);}});
test('startup server read is bounded by the existing verification deadline',async()=>{const f=account(true,null);f.c.withSessionVerificationDeadline=async()=>{throw Object.assign(Error('timeout'),{code:'schoolhub/deadline-exceeded'});};await assert.rejects(f.c.schoolAccountForStartup({uid:'teacher'}),e=>e.code==='schoolhub/deadline-exceeded');});
function worker(){const handlers={},stored=new Map(),opened=[],events=[],old=new Map();const cache={put:async(k,v)=>stored.set(typeof k==='string'?k:k.url,v),match:async k=>stored.get(typeof k==='string'?k:k.url)};const c={URL,Map,Response,self:{location:{href:'https://app.test/sw.js',origin:'https://app.test'},addEventListener:(n,f)=>handlers[n]=f,skipWaiting:async()=>events.push('activated'),clients:{matchAll:async()=>[],openWindow:async u=>opened.push(u),claim:async()=>{}}},caches:{open:async()=>cache,keys:async()=>[],delete:async()=>{}},fetch:async url=>({ok:true,url,clone(){return this;}})};vm.createContext(c);vm.runInContext(sw,c);return {c,handlers,stored,opened,events};}
test('update installs every referenced offline library before activation; cold-start scripts load without network',async()=>{const f=worker();let install;f.handlers.install({waitUntil:p=>install=p});await install;const html=fs.readFileSync('index.html','utf8');const vendors=[...html.matchAll(/<script src="(https:\/\/(?:www\.gstatic\.com|cdnjs\.cloudflare\.com)[^"]+)"/g)].map(x=>x[1]);assert.equal(vendors.length,8);assert(vendors.every(x=>f.stored.has(x)));f.c.fetch=async()=>{throw Error('offline');};for(const url of vendors)assert.equal((await f.c.cacheFirst({url})).url,url);assert.deepEqual(f.events,['activated']);});
test('failed Firebase dependency prevents an incomplete new worker from activating',async()=>{const f=worker();f.c.fetch=async url=>({ok:!url.includes('firebase-auth-compat'),url});let install;f.handlers.install({waitUntil:p=>install=p});await assert.rejects(install,/Incomplete app shell/);assert.equal(f.events.length,0);});
test('notification tap focuses an existing app window without navigation or restart',async()=>{const f=worker(),actions=[];const client={url:'https://app.test/',visibilityState:'visible',focus:async()=>actions.push('focus'),postMessage:m=>actions.push(m.type)};f.c.self.clients.matchAll=async()=>[{url:'https://other.test/',focus:()=>assert.fail('wrong app')},client];let work;f.handlers.notificationclick({notification:{close:()=>actions.push('close')},waitUntil:p=>work=p});await work;assert.deepEqual(actions,['close','focus','OPEN_NOTIFICATIONS']);assert.equal(f.opened.length,0);});
test('notification tap opens the app only when no existing app window survives',async()=>{const f=worker();let work;f.handlers.notificationclick({notification:{close(){}},waitUntil:p=>work=p});await work;assert.deepEqual(f.opened,['./?notifications=1']);});
