const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const source=fs.readFileSync('app-4.js','utf8'),storage=source.slice(source.indexOf('const SYNC_OUTBOX_KEY'),source.indexOf('// currentUid')),handler=source.slice(source.indexOf('const studentCreatePending'),source.indexOf('// Keep record IDs across retries'));
function fixture(values=new Map()){
 if(!values.has('students'))values.set('students',JSON.stringify([{id:'real',classId:'c4',name:'Existing pupil'}]));
 let click,cloud=0;const nodes={};for(const id of ['studentClassSelect','newStudentName','newStudentDob','addStudentValidation','newStudentGender','newStudentId','newStudentPhone','newStudentDisability','newStudentGuardian','newStudentHouseGps','addStudentBtn','studentSearchInput'])nodes[id]={value:'',textContent:'Add',classList:{add(){},remove(){}},addEventListener(_,fn){click=fn;}};
 nodes.studentClassSelect.value='c4';nodes.newStudentName.value='New pupil';nodes.newStudentDob.value='2015-01-01';nodes.newStudentGender.value='Male';nodes.studentSearchInput.value='Only test pupil';
 const c={console,navigator:{onLine:false},localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)},stripImagesForLocalStorage:(_,v)=>v,restoreLocalImagesForDbKey:(_,v)=>v,stableSyncJson:JSON.stringify,updateOfflineModeBanner(){},scheduleCloudPush(){},document:{getElementById:id=>nodes[id]},KEYS:{students:'students'},FIREBASE_ENABLED:true,currentUid:'teacher',currentSchoolId:'school',currentStatus:'active',sessionGeneration:1,sessionReady:true,sessionDataReady:true,cloudHydrationInProgress:false,offlineAuthenticatedMode:true,requireClassAccess:id=>id==='c4',uid:()=> 'new',isCurrentSession:()=>true,schoolRef(){cloud++;throw Error('Unexpected cloud call');},alert:m=>c.messages.push(m),messages:[],newStudentAge:{value:''},addStudentForm:{classList:{add(){}}},toggleAddStudentBtn:{setAttribute(){}},renderStudents(){},renderClasses(){},auditAction(){}};
 vm.createContext(c);vm.runInContext(storage+'\nglobalThis.db=DB;',c);vm.runInContext(handler,c);return{c,nodes,values,click:()=>click(),cloud:()=>cloud};
}
test('offline new pupil keeps the entire class, clears search, and survives reopening with pending intent',async()=>{const f=fixture();await f.click();assert.equal(f.cloud(),0);assert.equal(f.nodes.studentSearchInput.value,'');assert.equal(f.nodes.addStudentBtn.disabled,false);const reopened=fixture(f.values);assert.deepEqual(Array.from(reopened.c.db.get('students',[]),x=>x.name),['Existing pupil','New pupil']);assert.deepEqual(JSON.parse(f.values.get('arc_sync_outbox_v1')).dirty.students,['new']);});
test('offline creation rejects inactive, unready and unassigned sessions',async()=>{for(const changes of [{currentStatus:'disabled'},{sessionDataReady:false},{cloudHydrationInProgress:true},{requireClassAccess:()=>false}]){const f=fixture();Object.assign(f.c,changes);await f.click();assert.equal(f.c.db.get('students',[]).length,1);assert(!f.values.has('arc_sync_outbox_v1'));}});
