const fs=require('fs');
const assert=require('assert');
const js=fs.readFileSync('app-4.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
assert(js.includes("const SYNC_OUTBOX_KEY = 'arc_sync_outbox_v1'"));
assert(js.includes("const VERIFIED_SESSION_PREFIX = 'arc_verified_session_v1__'"));
assert(js.includes('function saveVerifiedLocalSession(user, data)'));
assert(js.includes('function loadVerifiedLocalSession(user)'));
assert(js.includes('function startCachedAuthenticatedSession(user, cached)'));
assert(js.includes('async function flushPendingCloudWrites()'));
assert(js.includes('async function revalidateAndSyncAfterReconnect()'));
assert(js.includes('Local offline edits go first so a cloud pull cannot overwrite them.'));
assert(js.includes('persistSyncOutbox();'));
assert(js.includes("window.addEventListener('offline'"));
assert(js.includes("window.addEventListener('online'"));
assert(html.includes('id="offlineModeBanner"'));
assert(sw.includes('schoolhub-cache-v40-sync-reports-3'));
console.log('offline-first authenticated mode regression: PASS');
